// SPDX-FileCopyrightText: 2026 Tyler Michael Bosworth
// SPDX-License-Identifier: LicenseRef-Eidovara-Source-Available-1.0
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('soul', {
  send: (m, opts) => ipcRenderer.invoke('soul:send', m, opts || {}), snapshot: () => ipcRenderer.invoke('soul:snapshot'), reset: () => ipcRenderer.invoke('soul:reset'),
  recordMedia: input => ipcRenderer.invoke('soul:recordMedia', input), entertainment: () => ipcRenderer.invoke('soul:entertainment'),
  remember: (c, opts) => ipcRenderer.invoke('soul:remember', c, opts), forget: x => ipcRenderer.invoke('soul:forget', x),
  newConversation: () => ipcRenderer.invoke('soul:newConversation'), selectConversation: id => ipcRenderer.invoke('soul:selectConversation', id), deleteConversation: id => ipcRenderer.invoke('soul:deleteConversation', id),
  getSettings: () => ipcRenderer.invoke('soul:getSettings'), acceptAgeGate: confirmed => ipcRenderer.invoke('soul:acceptAgeGate', confirmed), declineAgeGate: () => ipcRenderer.invoke('soul:declineAgeGate'), saveSettings: s => ipcRenderer.invoke('soul:saveSettings', s), diagnostics: () => ipcRenderer.invoke('soul:diagnostics'), openDataFolder: () => ipcRenderer.invoke('soul:openDataFolder'), selectLocalMedia: () => ipcRenderer.invoke('soul:selectLocalMedia'),
  createBackup: () => ipcRenderer.invoke('soul:createBackup'), listBackups: () => ipcRenderer.invoke('soul:listBackups'), restoreBackup: name => ipcRenderer.invoke('soul:restoreBackup', name), configureSetup: input => ipcRenderer.invoke('soul:configureSetup', input), configureAssistant: input => ipcRenderer.invoke('soul:configureAssistant', input), configureKernel: input => ipcRenderer.invoke('soul:configureKernel', input), kernelStatus: () => ipcRenderer.invoke('soul:kernelStatus'), workspace: (op, payload) => ipcRenderer.invoke('soul:workspace', op, payload), assistQuery: query => ipcRenderer.invoke('soul:assistQuery', query), selectCompanionImage: () => ipcRenderer.invoke('soul:selectCompanionImage'), addApplication: () => ipcRenderer.invoke('soul:addApplication'), discoverApplications: () => ipcRenderer.invoke('soul:discoverApplications'), addDiscoveredApplication: id => ipcRenderer.invoke('soul:addDiscoveredApplication', id), launchApplication: id => ipcRenderer.invoke('soul:launchApplication', id), removeApplication: id => ipcRenderer.invoke('soul:removeApplication', id), openExternal: url => ipcRenderer.invoke('soul:openExternal', url), checkForUpdates: () => ipcRenderer.invoke('soul:checkForUpdates'), installUpdate: () => ipcRenderer.invoke('soul:installUpdate'),
  adminLogin: password => ipcRenderer.invoke('soul:adminLogin', password), adminConfigure: password => ipcRenderer.invoke('soul:adminConfigure', password), adminStatus: () => ipcRenderer.invoke('soul:adminStatus'), adminSave: input => ipcRenderer.invoke('soul:adminSave', input), adminLogout: () => ipcRenderer.invoke('soul:adminLogout'), checkService: () => ipcRenderer.invoke('soul:checkService'), connectService: input => ipcRenderer.invoke('soul:connectService', input),
  evalCalc: query => ipcRenderer.invoke('soul:evalCalc', query),
  openOverlay: input => ipcRenderer.invoke('soul:openOverlay', input || {}),
  overlayStatus: () => ipcRenderer.invoke('soul:overlayStatus')
});
