[
  ".gitignore excludes proper files",
  "AGE.md explicitly states 18+ requirement",
  "TERMS.md commerce section is clear about no live payments",
  "all legal documents have 2026 copyright",
  "chatbot knowledge answers golden product questions",
  "check script validates all first-party JS syntax",
  "confirm-launch and age gate tests remain in the shipped surface",
  "current source keeps kernel, official api.eidovara.org, and the live installer metadata",
  "dependabot configured for npm and GitHub Actions security",
  "download page advertises exactly the canonical installer with integrity metadata",
  "first-party JS carries SPDX source-available headers and does not donate OSS rights",
  "footer pages have consistent source-available claims",
  "historical release hashes stay in CHANGELOG; live pages advertise only the current installer",
  "in-app legal overlay does not claim Apple, payments, or consciousness",
  "ip-certification inventory exists, is honest, and every listed path is present",
  "legal-instrument pack is templates and notices, not registrations or OSI giveaway",
  "marketing claims policy is consistent with source-available model",
  "network, security, and licensing docs match current fail-closed v0.19.1 surface",
  "no file contains encoding-corruption signatures",
  "no source file predicts consciousness or sentience for Soul",
  "no third-party brand names used as product feature names",
  "primary download CTA points at the published installer and keeps the age gate",
  "public nav Download uses nav-cta to download.html on every HTML page",
  "public release pages advertise the real current installer",
  "public site exposes nav, legal, assist, and 404 pages",
  "public site wires display marks, wallpapers, and OG image without CSP or token drift",
  "site CSP allows only same-origin scripts and no unsafe-inline/eval",
  "site helper download pointers match the canonical installer without importing app code",
  "website helper hrefs stay HTTPS or same-origin html",
  "website legal pages cover terms, privacy, age, and Apple disclaimer"
]
