// SPDX-FileCopyrightText: 2026 Soul Consciousness Studios
// SPDX-License-Identifier: LicenseRef-Eidovara-Source-Available-1.0
(() => {
  const messages = {
    en: {
      newConversation: 'ï¼‹ New conversation', dashboard: 'Dashboard', apps: 'Apps & Gaming', entertainment: 'Entertainment', memory: 'Memory', identity: 'Identity', settings: 'Settings', language: 'Interface language', save: 'Save settings',
      adultConfirm: 'Confirm legal-adult status', adultEnable: 'Enable Adult Soul',
      adultWarning: 'Adult Soul is only for people who have reached the age of majority where they are located. It must not be used by minors. This local confirmation is not independent identity or age verification. Confirm that you are legally an adult to continue.',
      dashboardTitle: 'Your Eidovara workspace', dashboardLead: 'Apps, gaming, media, research, backups, and a local companion that can open those surfaces. Optional Soul is a software self-model â€” not consciousness, not the website helper.',
      appsTitle: 'Apps & Gaming Hub', appsLead: 'Organize trusted Windows applications and ask Windows to launch them. Compatibility varies; Eidovara does not inject into or control them.',
      discoverApps: 'Discover installed apps', chooseFile: 'ï¼‹ Choose file', gamingMode: 'Gaming mode', gamingModeLead: 'Reduces Eidovaraâ€™s animated lighting and transparency while you play. It does not change another gameâ€™s process or frame rate.', lowOverhead: 'Low-overhead mode',
      entertainmentTitle: 'Entertainment', entertainmentLead: 'Local taste, queue helpers, and lawful platform handoff â€” Spotify, YouTube, and Internet Archive stay official HTTPS searches.',
      emptyAppsTitle: 'No applications linked yet', emptyAppsBody: 'Build a Windows shelf of titles you already trust and are permitted to use.',
      emptyAppsStep1: 'Discover Start Menu shortcuts on this PC, or choose a .exe / .lnk file.', emptyAppsStep2: 'Launch is confirmation-only. Eidovara does not inject into games or bypass anti-cheat.', emptyAppsStep3: 'Free editions keep up to three linked apps; Premium testing can raise that locally.',
      emptyFavorites: 'Favorite media will appear here after you heart something in the player.', emptyRecent: 'Play, skip, and complete events will appear here. Local file paths are not stored in taste records.', emptyMemory: 'No durable memories yet.',
      focusSession: 'Focus session', gamingStream: 'Gaming & stream', study: 'Study', create: 'Create', research: 'Research', reviewMemory: 'Review memory',
      moodMix: 'Mood mix', fromFavorites: 'From favorites', watchSomething: 'Watch something', gamingSoundtrack: 'Gaming soundtrack', studySoundtrack: 'Study soundtrack', surpriseMe: 'Surprise me',
      favoriteMedia: 'Favorite media', recentActivity: 'Recent activity', mixHelper: 'Queue helper', mixEmpty: 'Play or favorite something to grow a local mix. Suggestions stay on this device.',
      platformTitle: 'Platform connections', platformLead: 'Spotify, YouTube, and Internet Archive open official searches in your system browser. Eidovara does not capture credentials, bypass subscriptions, download protected streams, inject into other players, or imply affiliation.',
      openLocalMedia: 'Open local media',
      setupTitle: 'What do you need Soul for?', setupLead: 'Choose any roles that fit. You can change this later in Settings.',
      roleGaming: 'Gaming & editing assistant', roleGamingLead: 'Game planning, clips, creative editing, and workflows.',
      roleStream: 'Stream helper', roleStreamLead: 'Streaming goals, OBS preparation, scenes, inputs, and checklists. Direct OBS control is not in this release.',
      roleStudy: 'Studying assistant', roleStudyLead: 'Explanations, review plans, research, and practice.',
      rolePersonal: 'Personal usage', rolePersonalLead: 'Conversation, planning, memory, and everyday assistance.',
      roleCreative: 'Creative projects', roleCreativeLead: 'Writing, ideas, music discovery, and media.',
      roleWork: 'Work & productivity', roleWorkLead: 'Organization, drafting, decisions, and task support.',
      roleAccess: 'Accessibility support', roleAccessLead: 'Readable pacing, reduced motion, keyboard-first steps, and related workspace needs.',
      setupCustom: 'Anything else Soul should understand?', setupAccess: 'Accessibility or interaction needs', saveContinue: 'Save and continue', cancel: 'Cancel',
      nextConfigure: 'Configure roles', nextAddApps: 'Add a trusted app', nextMemory: 'Review memory', nextBackup: 'Create a backup', nextSettings: 'Open settings', nextEntertainment: 'Open Entertainment', nextDiagnostics: 'Show diagnostics',
      backupTitle: 'Backups', backupLead: 'Create a portable local snapshot or restore an earlier snapshot. Encrypted when Windows protection is available.',
      createBackup: 'Create backup', refreshList: 'Refresh list', restoreBackup: 'Restore selected backup', noBackups: 'No backups yet. Create one before changing providers or resetting.',
      diagShow: 'Show diagnostics', diagLead: 'Local snapshot of this installation. Not a security certification or compatibility guarantee.',
      behaviorSaved: 'Behavior settings saved. Language, tone, and accessibility remain as set.',
      dashFocus: 'Focus', dashRoles: 'Roles', dashMemory: 'Memory', dashApps: 'Apps', dashMedia: 'Entertainment', dashPrivacy: 'Workspace', dashBackups: 'Backups', dashHealth: 'Diagnostics',
      companionTitle: 'Workspace companion', companionLead: 'Local answers. Conversations stay on this PC. Ctrl+/ to focus.',
      companionApps: 'Apps', companionMedia: 'Media', companionMemory: 'Memory', companionLegal: 'Legal', companionStatus: 'Status', companionHelp: 'Help',
      overlayTitle: 'Workspace overlays', overlayLead: 'Floating Eidovara windows for Soul chat, HTTPS browsing, and Discordâ€™s own website. Not an official Discord overlay. Does not inject into other games. Assist never receives Discord tokens.',
      overlayChat: 'Soul chat overlay', overlayBrowse: 'Browse overlay', overlayDiscord: 'Discord guest', overlayGo: 'Open in browse overlay', overlayUrlLabel: 'HTTPS address for the browse overlay', overlayKeys: 'Ctrl+Shift+O jumps here. Ctrl+K also lists overlays. Esc closes an overlay unless you are typing in the guest page.',
      overlayHelp: 'Overlays are Eidovara windows. Discord is their website in a sandboxed guest session â€” not an official Discord overlay, not affiliated, and not injection into other games. Guest browsing is HTTPS you open. Assist never receives Discord tokens or guest DOM.',
      playDeskTitle: 'Play desk', playDeskLead: 'Confirm-launched library recents, Eidovara overlays, and this processâ€™s CPU/memory. Not a Steam overlay and not other-game telemetry.',
      playRecentsEmpty: 'Confirm-launch a linked app to see it here. Eidovara does not scrape other games.',
      overlayRecentsEmpty: 'HTTPS pages you open in the browse overlay appear here. Local only.',
      overlayMetricsRefresh: 'Refresh Eidovara process metrics', overlayMetricsOff: 'Process metrics unavailable in this session.',
      shortcutOverlays: 'Jump to workspace overlays (chat, browse, Discord guest). In-app only.',
      companionAskLabel: 'Ask the workspace companion', companionNote: 'Local only Â· not a cloud chat Â· Assist is not Soul Â· no live payments',
      companionEmptyTitle: 'Ask this workspace.', companionEmpty: 'Local answers from product facts and your on-device profile. Nothing is sent to the website helper or Worker /v1/assist.',
      companionSoulOn: 'Soul is a software self-model on this device â€” not a claim of consciousness.',
      companionSoulOff: 'Optional Soul setup is off. This companion is not Soul and is not conscious.',
      companionOffline: 'Local-only. Conversations stay on this PC. Service not attached.',
      companionServiceDown: 'Local-only. Attached service is unreachable; the workspace still works.',
      companionServiceIdle: 'Local conversations. Service is health/status only â€” chat is not sent.',
      companionThinking: 'Working locallyâ€¦',
      notConfigured: 'not configured', offlineFirst: 'offline-first', connectedProvider: 'connected provider',
      mediaDisabled: 'Media playback is disabled in Soul behavior settings.', mediaConfirm: 'Play this media in Eidovara:',
      launchApp: 'Launch', launchCancelled: 'Launch cancelled.',
      premiumLocked: 'Free: offline/local models, Wikipedia/Wikimedia research, up to 3 apps. RGB, Brave key, and remote endpoints stay Premium.',
      premiumUnlocked: 'Premium test gates are on: remote endpoints, Brave search key, RGB, and unlimited apps.',
      soulDockTitle: 'Soul', soulLive: 'Soul is live on this PC', soulIdle: 'Soul kernel idle',
      companionTitle: 'Soul companion', companionLead: 'Always-on session kernel on this PC. Software, not a person. Assist is not Soul.',
      companionEmpty: 'Ask from this dock. Local kernel answers on this PC. Assist is not Soul.',
      companionNote: 'Local kernel Â· Assist is not Soul Â· no live payments Â· voices from Windows',
      companionAskLabel: 'Ask Soul', presenceCaption: 'Decorative presence â€” not a conscious figure.',
      companionResearchNote: 'Public lookup after you asked â€” not a full-internet index.',
      confirmOpenLink: 'Open this HTTPS page in your browser?',
      researchTitle: 'Research', researchLead: 'Public web lookup after you ask. Not a full-internet index. Wikipedia/Wikimedia, Internet Archive, optional keyed search, pages you open, plus official YouTube/Spotify/Archive search links. Local files play in Eidovara.',
      researchNav: 'Research',
      researchCopy: 'Public web lookup after you ask. Not a full-internet index. Wikipedia/Wikimedia, Internet Archive, optional keyed search, pages you open, plus official YouTube/Spotify/Archive search links. Local files play in Eidovara.',
      researchEmptyTitle: 'No lookup yet', researchEmpty: 'Ask me to search the internet for a topic, or include an HTTPS URL after an explicit internet/web/online request. This is not a crawl of the whole internet.',
      researchIdle: 'no lookup yet', researchResults: 'Internet results', openInBrowser: 'Open in browser',
      researchLookup: 'Look up', researchTopicLabel: 'Topic or HTTPS page', dashResearch: 'Research', nextResearch: 'Open Research',
      handoffNote: 'Official HTTPS search in your browser. Eidovara does not fetch that siteâ€™s HTML or capture logins.',
      sessionLibrary: 'This sessionâ€™s local library', discoveryTitle: 'Local library & official searches',
      emptyLibrary: 'Open a local audio or video file to play it in Eidovara. Paths stay out of taste records.',
      emptyDiscovery: 'Ask for music, a watch, or a mood mix to show local matches and official YouTube/Spotify/Archive search chips.',
      playInEidovara: 'Play in Eidovara', playLocal: 'Play', localNow: 'this device',
      researchIssue: 'Internet search issue:', modelIssue: 'Model connection issue:',
      paletteTitle: 'Jump in Eidovara', paletteLead: 'Local jump and search. No background crawler. Linked apps still confirm-launch. Assist is not Soul.', paletteOpen: 'Jump (Ctrl+K)', paletteHint: 'â†‘â†“ to move Â· Enter to run Â· Esc to close Â· Ctrl+K', paletteEmpty: 'No local matches. Search stays on this PC.',
      cheatsheetTitle: 'Keyboard cheatsheet', cheatsheetLead: 'Eidovara shortcuts. This overlay is in-app only â€” it does not inject into games or other processes.', cheatsheetOpen: 'Shortcuts',
      recentsTitle: 'Recents', recentsLead: 'Linked apps you confirm-launched, local media titles, and memories you opened â€” on this PC only.', recentsEmpty: 'Nothing recent yet.',
      notifyTitle: 'In-app notices', notifyLead: 'Local events from this workspace. Not OS toast spam and not telemetry.', notifyClear: 'Clear', notifyEmpty: 'No notices yet.',
      sleepTimer: 'Sleep timer', sleepOff: 'Off', sleep15: '15 min', sleep30: '30 min', sleep60: '60 min',
      nowPlaying: 'Now playing', trayStay: 'Keep running in the tray', alwaysOnTop: 'Keep window on top', openAtLogin: 'Open at Windows sign-in', pinCompanion: 'Pin companion dock', chromeHelp: 'Tray, on-top, and sign-in apply to this Eidovara window only.',
      focusQuiet: 'Focus session', focusQuietNote: 'Local timer. Other apps are not closed or injected into.', focusStart: 'Start 25 minutes', focusStop: 'Stop',
      scratchTitle: 'Scratchpad', scratchHint: 'Stays on this PC', scratchPlaceholder: 'Quick capture. Stays on this device.', scratchCapture: 'Capture to Memory',
      pinWidget: 'Pin a tile', unpinWidget: 'Unpin',      welcomeTitle: 'You\'re in. Start on the Dashboard.', welcomeLead: 'Eidovara is this Windows workspace. Soul (right side) is the local assistant â€” a software self-model, not a mind. Assist is an optional Worker helper and stays off until you turn it on. They are not the same thing.',
      welcomeDashboard: 'Open Dashboard', settingsTitle: 'Settings', settingsLead: 'Grouped by what you change. Soul stays on this PC. Assist stays off unless you turn it on. No live payments.',
      startPathTitle: 'Start here', startPathLead: 'One path after you confirm 18+. You can hide this card anytime.',
      startPathStep1: 'This Dashboard is home. Cards below open the real surfaces.',
      startPathStep2: 'Soul (right dock) is the local software self-model. Ask it here. It is not a person and not the website helper.',
      startPathStep3: 'Assist is an optional Worker helper. It stays off unless you enable it in Settings. Assist is not Soul.',
      startTalk: 'Talk with Soul', startApps: 'Add a trusted app', startSettings: 'Open Settings', startDismiss: 'Hide this guide',
      companionPanelTitle: 'Workspace companion',
      companionHere: 'What you can do here', whatHere: 'What can you do here?', companionEmptyHint: 'Type a next step, or ask â€œwhat can you do here?â€ Local kernel only. Assist is not Soul.',
      paletteEmpty: 'No matching places. Try dashboard or settings.',
      paletteTitle: 'Jump in Eidovara', scratchTitle: 'Scratchpad', scratchHint: 'Stays on this PC', scratchCapture: 'Capture to Memory', scratchPlaceholder: 'Quick capture. Stays on this device.',
      focusQuiet: 'Focus session', focusStart: 'Start 25 minutes', focusStop: 'Stop', pinWidget: 'Pin a tile', unpinWidget: 'Unpin'
    },
    es: {
      newConversation: 'ï¼‹ Nueva conversaciÃ³n', dashboard: 'Panel', apps: 'Aplicaciones y juegos', entertainment: 'Entretenimiento', memory: 'Memoria', identity: 'Identidad', settings: 'ConfiguraciÃ³n', language: 'Idioma de la interfaz', save: 'Guardar configuraciÃ³n',
      adultConfirm: 'Confirmar mayorÃ­a de edad legal', adultEnable: 'Activar Soul para adultos',
      adultWarning: 'Soul para adultos es solo para personas que hayan alcanzado la mayorÃ­a de edad donde se encuentren. Los menores no deben usarlo. Esta confirmaciÃ³n local no verifica de forma independiente la identidad ni la edad. Confirma que eres legalmente adulto para continuar.',
      dashboardTitle: 'Tu espacio Eidovara', dashboardLead: 'Apps, juegos, medios, investigaciÃ³n, copias y un compaÃ±ero local que abre esas superficies. Soul opcional es un modelo de software, no consciencia ni el asistente del sitio.',
      appsTitle: 'Centro de aplicaciones y juegos', appsLead: 'Organiza aplicaciones de Windows de confianza y pide a Windows que las abra. La compatibilidad varÃ­a; Eidovara no inyecta ni las controla.',
      discoverApps: 'Descubrir apps instaladas', chooseFile: 'ï¼‹ Elegir archivo', gamingMode: 'Modo de juego', gamingModeLead: 'Reduce la iluminaciÃ³n y transparencia de Eidovara mientras juegas. No cambia el proceso ni los FPS de otro juego.', lowOverhead: 'Modo de bajo consumo',
      entertainmentTitle: 'Entretenimiento', entertainmentLead: 'Gusto local, ayudas de cola y transferencia lÃ­cita: Spotify, YouTube e Internet Archive siguen siendo bÃºsquedas HTTPS oficiales.',
      emptyAppsTitle: 'AÃºn no hay aplicaciones vinculadas', emptyAppsBody: 'Arma un estante de Windows con tÃ­tulos que ya confÃ­as y puedes usar.',
      emptyAppsStep1: 'Descubre accesos del menÃº Inicio, o elige un archivo .exe / .lnk.', emptyAppsStep2: 'El lanzamiento es solo con confirmaciÃ³n. Eidovara no inyecta juegos ni evade anti-cheat.', emptyAppsStep3: 'La ediciÃ³n gratuita permite hasta tres apps; Premium de prueba puede subir ese lÃ­mite en local.',
      emptyFavorites: 'Los favoritos aparecerÃ¡n cuando marques algo en el reproductor.', emptyRecent: 'Reproducciones, omisiones y cierres aparecerÃ¡n aquÃ­. Las rutas locales no se guardan en el gusto.', emptyMemory: 'AÃºn no hay recuerdos duraderos.',
      focusSession: 'SesiÃ³n de enfoque', gamingStream: 'Juegos y stream', study: 'Estudio', create: 'Crear', research: 'Investigar', reviewMemory: 'Revisar memoria',
      moodMix: 'Mezcla de Ã¡nimo', fromFavorites: 'Desde favoritos', watchSomething: 'Ver algo', gamingSoundtrack: 'Banda de juego', studySoundtrack: 'Banda de estudio', surpriseMe: 'SorprÃ©ndeme',
      favoriteMedia: 'Medios favoritos', recentActivity: 'Actividad reciente', mixHelper: 'Ayuda de cola', mixEmpty: 'Reproduce o marca un favorito para armar una mezcla local. Las sugerencias se quedan en este dispositivo.',
      platformTitle: 'Conexiones de plataforma', platformLead: 'Spotify, YouTube e Internet Archive abren bÃºsquedas oficiales en el navegador. Eidovara no captura credenciales, evita suscripciones, descarga streams protegidos, inyecta otros reproductores ni implica afiliaciÃ³n.',
      openLocalMedia: 'Abrir medio local',
      setupTitle: 'Â¿Para quÃ© necesitas a Soul?', setupLead: 'Elige los roles que encajen. Puedes cambiarlos luego en ConfiguraciÃ³n.',
      roleGaming: 'Asistente de juegos y ediciÃ³n', roleGamingLead: 'Plan de partidas, clips, ediciÃ³n creativa y flujos.',
      roleStream: 'Ayuda de streaming', roleStreamLead: 'Objetivos, preparaciÃ³n de OBS, escenas y listas. El control directo de OBS no estÃ¡ en esta versiÃ³n.',
      roleStudy: 'Asistente de estudio', roleStudyLead: 'Explicaciones, planes de repaso, investigaciÃ³n y prÃ¡ctica.',
      rolePersonal: 'Uso personal', rolePersonalLead: 'ConversaciÃ³n, planificaciÃ³n, memoria y ayuda cotidiana.',
      roleCreative: 'Proyectos creativos', roleCreativeLead: 'Escritura, ideas, descubrimiento musical y medios.',
      roleWork: 'Trabajo y productividad', roleWorkLead: 'OrganizaciÃ³n, borradores, decisiones y tareas.',
      roleAccess: 'Apoyo de accesibilidad', roleAccessLead: 'Ritmo legible, menos movimiento, pasos con teclado y necesidades afines.',
      setupCustom: 'Â¿Algo mÃ¡s que Soul deba entender?', setupAccess: 'Necesidades de accesibilidad o interacciÃ³n', saveContinue: 'Guardar y continuar', cancel: 'Cancelar',
      nextConfigure: 'Configurar roles', nextAddApps: 'AÃ±adir app de confianza', nextMemory: 'Revisar memoria', nextBackup: 'Crear copia', nextSettings: 'Abrir configuraciÃ³n', nextEntertainment: 'Abrir Entretenimiento', nextDiagnostics: 'Ver diagnÃ³sticos',
      backupTitle: 'Copias de seguridad', backupLead: 'Crea una instantÃ¡nea local o restaura una anterior. Cifrada cuando Windows lo permite.',
      createBackup: 'Crear copia', refreshList: 'Actualizar lista', restoreBackup: 'Restaurar copia seleccionada', noBackups: 'AÃºn no hay copias. Crea una antes de cambiar de proveedor o restablecer.',
      diagShow: 'Mostrar diagnÃ³sticos', diagLead: 'InstantÃ¡nea local de esta instalaciÃ³n. No es una certificaciÃ³n de seguridad ni una garantÃ­a de compatibilidad.',
      behaviorSaved: 'Comportamiento guardado. Idioma, tono y accesibilidad se mantienen.',
      dashFocus: 'Enfoque', dashRoles: 'Roles', dashMemory: 'Memoria', dashApps: 'Apps', dashMedia: 'Entretenimiento', dashPrivacy: 'Espacio', dashBackups: 'Copias', dashHealth: 'DiagnÃ³stico',
      companionTitle: 'CompaÃ±ero del espacio', companionLead: 'Respuestas locales. Las conversaciones quedan en este PC. Ctrl+/ para enfocar.',
      companionApps: 'Apps', companionMedia: 'Medios', companionMemory: 'Memoria', companionLegal: 'Legal', companionStatus: 'Estado', companionHelp: 'Ayuda',
      overlayTitle: 'Overlays del espacio', overlayLead: 'Ventanas flotantes de Eidovara para el chat Soul, navegaciÃ³n HTTPS y el propio sitio de Discord. No es un overlay oficial de Discord. No se inyecta en otros juegos. Assist no recibe tokens de Discord.',
      overlayChat: 'Overlay de chat Soul', overlayBrowse: 'Overlay de navegaciÃ³n', overlayDiscord: 'Discord invitado', overlayGo: 'Abrir en overlay de navegaciÃ³n', overlayUrlLabel: 'DirecciÃ³n HTTPS para el overlay de navegaciÃ³n', overlayKeys: 'Ctrl+Shift+O salta aquÃ­. Ctrl+K tambiÃ©n lista overlays. Esc cierra un overlay salvo si escribes en la pÃ¡gina invitada.',
      overlayHelp: 'Los overlays son ventanas de Eidovara. Discord es su sitio en una sesiÃ³n invitada aislada: no es un overlay oficial, no hay afiliaciÃ³n ni inyecciÃ³n en otros juegos. Assist no recibe tokens de Discord ni el DOM invitado.',
      playDeskTitle: 'Mesa de juego', playDeskLead: 'Recientes de apps lanzadas con confirmaciÃ³n, overlays de Eidovara y CPU/memoria de este proceso. No es un overlay de Steam ni telemetrÃ­a de otros juegos.',
      playRecentsEmpty: 'Lanza con confirmaciÃ³n una app vinculada para verla aquÃ­. Eidovara no inspecciona otros juegos.',
      overlayRecentsEmpty: 'Las pÃ¡ginas HTTPS que abras en el overlay de navegaciÃ³n aparecen aquÃ­. Solo local.',
      overlayMetricsRefresh: 'Actualizar mÃ©tricas del proceso Eidovara', overlayMetricsOff: 'MÃ©tricas de proceso no disponibles en esta sesiÃ³n.',
      shortcutOverlays: 'Saltar a overlays del espacio (chat, navegaciÃ³n, Discord invitado). Solo en la app.',
      companionAskLabel: 'Preguntar al compaÃ±ero del espacio', companionNote: 'Solo local Â· no es chat en la nube Â· Assist no es Soul Â· sin pagos en vivo',
      companionEmptyTitle: 'Pregunta a este espacio.', companionEmpty: 'Respuestas locales con hechos del producto y tu perfil en el dispositivo. Nada se envÃ­a al asistente del sitio ni a Worker /v1/assist.',
      companionSoulOn: 'Soul es un modelo de software en este dispositivo, no una afirmaciÃ³n de consciencia.',
      companionSoulOff: 'La configuraciÃ³n opcional de Soul estÃ¡ apagada. Este compaÃ±ero no es Soul y no es consciente.',
      companionOffline: 'Solo local. Las conversaciones quedan en este PC. Servicio no conectado.',
      companionServiceDown: 'Solo local. El servicio conectado no responde; el espacio sigue funcionando.',
      companionServiceIdle: 'Conversaciones locales. El servicio es solo salud/estado: el chat no se envÃ­a.',
      companionThinking: 'Trabajando en localâ€¦',
      notConfigured: 'sin configurar', offlineFirst: 'primero local', connectedProvider: 'proveedor conectado',
      mediaDisabled: 'La reproducciÃ³n estÃ¡ desactivada en el comportamiento de Soul.', mediaConfirm: 'Reproducir este medio en Eidovara:',
      launchApp: 'Abrir', launchCancelled: 'Lanzamiento cancelado.',
      premiumLocked: 'Gratis: modelos locales, Wikipedia/Wikimedia, hasta 3 apps. RGB, clave Brave y endpoints remotos son Premium.',
      premiumUnlocked: 'Prueba Premium activa: endpoints remotos, clave Brave, RGB y apps ilimitadas.',
      soulDockTitle: 'Soul', soulLive: 'Soul estÃ¡ en vivo en este PC', soulIdle: 'Kernel de Soul inactivo',
      companionTitle: 'CompaÃ±ero Soul', companionLead: 'NÃºcleo de sesiÃ³n siempre disponible en este PC. Software, no una persona. Assist no es Soul.',
      companionEmpty: 'Pregunta desde este panel. El nÃºcleo local responde en este PC. Assist no es Soul.',
      companionNote: 'NÃºcleo local Â· Assist no es Soul Â· sin pagos en vivo Â· voces de Windows',
      companionAskLabel: 'Preguntar a Soul', presenceCaption: 'Presencia decorativa: no es una figura consciente.',
      companionResearchNote: 'Consulta pÃºblica despuÃ©s de que lo pediste â€” no es un Ã­ndice de todo internet.',
      confirmOpenLink: 'Â¿Abrir esta pÃ¡gina HTTPS en el navegador?',
      researchNav: 'Investigar',
      researchTitle: 'InvestigaciÃ³n',
      researchLead: 'Consulta web pÃºblica cuando lo pides. No es un Ã­ndice de todo internet. Wikipedia/Wikimedia, Internet Archive, bÃºsqueda con clave opcional, pÃ¡ginas que abres y enlaces oficiales de YouTube/Spotify/Archive.',
      researchCopy: 'Consulta web pÃºblica cuando lo pides. No es un Ã­ndice de todo internet. Wikipedia/Wikimedia, Internet Archive, bÃºsqueda con clave opcional, pÃ¡ginas que abres y enlaces oficiales de YouTube/Spotify/Archive.',
      researchEmptyTitle: 'AÃºn no hay consulta', researchEmpty: 'PÃ­deme buscar en internet un tema, o incluye una URL HTTPS tras una peticiÃ³n explÃ­cita. Esto no rastrea todo internet.',
      researchIdle: 'sin consulta', researchResults: 'Resultados de internet', openInBrowser: 'Abrir en el navegador',
      researchLookup: 'Consultar', researchTopicLabel: 'Tema o pÃ¡gina HTTPS', dashResearch: 'InvestigaciÃ³n', nextResearch: 'Abrir InvestigaciÃ³n',
      handoffNote: 'BÃºsqueda HTTPS oficial en el navegador. Eidovara no descarga el HTML de ese sitio ni captura inicios de sesiÃ³n.',
      sessionLibrary: 'Biblioteca local de esta sesiÃ³n', discoveryTitle: 'Biblioteca local y bÃºsquedas oficiales',
      emptyLibrary: 'Abre un audio o video local para reproducirlo en Eidovara. Las rutas no se guardan en el gusto.',
      emptyDiscovery: 'Pide mÃºsica, algo para ver o una mezcla de Ã¡nimo para ver coincidencias locales y chips de YouTube/Spotify/Archive.',
      playInEidovara: 'Reproducir en Eidovara', playLocal: 'Reproducir', localNow: 'este dispositivo',
      researchIssue: 'Problema de bÃºsqueda en internet:', modelIssue: 'Problema de conexiÃ³n del modelo:',
      paletteTitle: 'Saltar en Eidovara', paletteLead: 'Salto y bÃºsqueda locales. Sin rastreador. Las apps vinculadas siguen pidiendo confirmaciÃ³n. Assist no es Soul.', paletteOpen: 'Saltar (Ctrl+K)', paletteHint: 'â†‘â†“ para mover Â· Intro para ejecutar Â· Esc para cerrar Â· Ctrl+K', paletteEmpty: 'Sin coincidencias locales. La bÃºsqueda se queda en este PC.',
      cheatsheetTitle: 'Atajos de teclado', cheatsheetLead: 'Atajos de Eidovara. Esta capa es solo dentro de la app; no se inyecta en juegos ni otros procesos.', cheatsheetOpen: 'Atajos',
      recentsTitle: 'Recientes', recentsLead: 'Apps que abriste con confirmaciÃ³n, tÃ­tulos de medios locales y recuerdos â€” solo en este PC.', recentsEmpty: 'AÃºn no hay recientes.',
      notifyTitle: 'Avisos en la app', notifyLead: 'Eventos locales de este espacio. No es spam del sistema ni telemetrÃ­a.', notifyClear: 'Borrar', notifyEmpty: 'AÃºn no hay avisos.',
      sleepTimer: 'Temporizador de apagado', sleepOff: 'Off', sleep15: '15 min', sleep30: '30 min', sleep60: '60 min',
      nowPlaying: 'Reproduciendo', trayStay: 'Seguir en la bandeja', alwaysOnTop: 'Mantener ventana al frente', openAtLogin: 'Abrir al iniciar Windows', pinCompanion: 'Fijar el compaÃ±ero', chromeHelp: 'Bandeja, siempre visible e inicio aplican solo a esta ventana de Eidovara.',
      focusQuiet: 'SesiÃ³n de enfoque', focusQuietNote: 'Temporizador local. No se cierran ni inyectan otras apps.', focusStart: 'Empezar 25 minutos', focusStop: 'Parar',
      scratchTitle: 'Bloc', scratchHint: 'Se queda en este PC', scratchPlaceholder: 'Captura rÃ¡pida. Se queda en este dispositivo.', scratchCapture: 'Capturar a Memoria',
      pinWidget: 'Fijar un mosaico', unpinWidget: 'Quitar',      welcomeTitle: 'Ya estÃ¡s dentro. Empieza en el Panel.', welcomeLead: 'Eidovara es este espacio de Windows. Soul (derecha) es el asistente local: un modelo de software, no una mente. Assist es un ayudante opcional y permanece apagado hasta que lo actives.',
      welcomeDashboard: 'Abrir Panel', settingsTitle: 'ConfiguraciÃ³n', settingsLead: 'Agrupado por lo que cambias. Soul se queda en este PC. Assist permanece apagado salvo que lo actives. No hay pagos en vivo.',
      startPathTitle: 'Empieza aquÃ­', startPathLead: 'Un camino claro despuÃ©s de confirmar 18+. Puedes ocultar esta tarjeta.',
      startPathStep1: 'Este Panel es el inicio. Las tarjetas abren las superficies reales.',
      startPathStep2: 'Soul (el muelle derecho) es el modelo de software local. PregÃºntale aquÃ­. No es una persona ni el ayudante del sitio.',
      startPathStep3: 'Assist es un ayudante opcional del Worker. Permanece apagado salvo que lo actives en ConfiguraciÃ³n. Assist no es Soul.',
      startTalk: 'Hablar con Soul', startApps: 'AÃ±adir app de confianza', startSettings: 'Abrir ConfiguraciÃ³n', startDismiss: 'Ocultar esta guÃ­a',
      paletteEmpty: 'NingÃºn lugar coincide. Prueba panel o configuraciÃ³n.',
      paletteTitle: 'Saltar en Eidovara', scratchTitle: 'Bloc', scratchHint: 'Se queda en este PC', scratchCapture: 'Capturar a Memoria', scratchPlaceholder: 'Captura rÃ¡pida. Se queda en este dispositivo.',
      focusQuiet: 'SesiÃ³n de enfoque', focusStart: 'Empezar 25 minutos', focusStop: 'Parar', pinWidget: 'Fijar mosaico', unpinWidget: 'Quitar',
      companionPanelTitle: 'CompaÃ±ero del espacio'
    },
    fr: {
      newConversation: 'ï¼‹ Nouvelle conversation', dashboard: 'Tableau de bord', apps: 'Applications et jeux', entertainment: 'Divertissement', memory: 'MÃ©moire', identity: 'IdentitÃ©', settings: 'ParamÃ¨tres', language: 'Langue de lâ€™interface', save: 'Enregistrer',
      adultConfirm: 'Confirmer la majoritÃ© lÃ©gale', adultEnable: 'Activer Soul adulte',
      adultWarning: 'Soul adulte est rÃ©servÃ© aux personnes ayant atteint lâ€™Ã¢ge de la majoritÃ© lÃ  oÃ¹ elles se trouvent. Les mineurs ne doivent pas lâ€™utiliser. Cette confirmation locale ne constitue pas une vÃ©rification indÃ©pendante de lâ€™identitÃ© ou de lâ€™Ã¢ge. Confirmez que vous Ãªtes lÃ©galement adulte pour continuer.',
      dashboardTitle: 'Votre espace Eidovara', dashboardLead: 'Apps, jeu, mÃ©dias, recherche, sauvegardes, et un compagnon local qui ouvre ces surfaces. Soul facultatif est un modÃ¨le logiciel â€” pas la conscience, pas lâ€™assistant du site.',
      appsTitle: 'Hub applications et jeux', appsLead: 'Organisez des applications Windows de confiance et demandez Ã  Windows de les lancer. La compatibilitÃ© varie ; Eidovara nâ€™injecte ni ne les contrÃ´le.',
      discoverApps: 'DÃ©couvrir les apps installÃ©es', chooseFile: 'ï¼‹ Choisir un fichier', gamingMode: 'Mode jeu', gamingModeLead: 'RÃ©duit lâ€™Ã©clairage et la transparence dâ€™Eidovara pendant que vous jouez. Cela ne change pas le processus ni les FPS dâ€™un autre jeu.', lowOverhead: 'Mode allÃ©gÃ©',
      entertainmentTitle: 'Divertissement', entertainmentLead: 'GoÃ»t local, aides de file et transfert licite â€” Spotify, YouTube et Internet Archive restent des recherches HTTPS officielles.',
      emptyAppsTitle: 'Aucune application liÃ©e', emptyAppsBody: 'Constituez une Ã©tagÃ¨re Windows de titres que vous avez le droit dâ€™utiliser.',
      emptyAppsStep1: 'DÃ©couvrez les raccourcis du menu DÃ©marrer, ou choisissez un .exe / .lnk.', emptyAppsStep2: 'Le lancement est confirmÃ©. Eidovara nâ€™injecte pas les jeux et nâ€™Ã©vite pas lâ€™anti-cheat.', emptyAppsStep3: 'Lâ€™Ã©dition gratuite garde jusquâ€™Ã  trois apps ; le test Premium peut lâ€™augmenter localement.',
      emptyFavorites: 'Les favoris apparaÃ®tront aprÃ¨s un cÅ“ur dans le lecteur.', emptyRecent: 'Lectures, ignores et fins apparaÃ®tront ici. Les chemins locaux ne sont pas stockÃ©s dans le goÃ»t.', emptyMemory: 'Pas encore de souvenirs durables.',
      focusSession: 'Session concentrÃ©e', gamingStream: 'Jeu et stream', study: 'Ã‰tude', create: 'CrÃ©er', research: 'Recherche', reviewMemory: 'Relire la mÃ©moire',
      moodMix: 'Mix dâ€™humeur', fromFavorites: 'Depuis les favoris', watchSomething: 'Regarder', gamingSoundtrack: 'Bande jeu', studySoundtrack: 'Bande Ã©tude', surpriseMe: 'Surprenez-moi',
      favoriteMedia: 'MÃ©dias favoris', recentActivity: 'ActivitÃ© rÃ©cente', mixHelper: 'Aide de file', mixEmpty: 'Lisez ou favoritez un mÃ©dia pour une mixte locale. Les suggestions restent sur cet appareil.',
      platformTitle: 'Connexions de plateformes', platformLead: 'Spotify, YouTube et Internet Archive ouvrent des recherches officielles dans le navigateur. Eidovara ne capture pas les identifiants, nâ€™Ã©vite pas les abonnements, ne tÃ©lÃ©charge pas les flux protÃ©gÃ©s, nâ€™injecte pas dâ€™autres lecteurs et nâ€™implique aucune affiliation.',
      openLocalMedia: 'Ouvrir un mÃ©dia local',
      setupTitle: 'Pour quoi avez-vous besoin de Soul ?', setupLead: 'Choisissez les rÃ´les adaptÃ©s. Modifiable plus tard dans ParamÃ¨tres.',
      roleGaming: 'Assistant jeu et montage', roleGamingLead: 'Plan de parties, clips, montage crÃ©atif et flux.',
      roleStream: 'Aide streaming', roleStreamLead: 'Objectifs, prÃ©paration OBS, scÃ¨nes et listes. Le contrÃ´le direct dâ€™OBS nâ€™est pas dans cette version.',
      roleStudy: 'Assistant dâ€™Ã©tude', roleStudyLead: 'Explications, plans de rÃ©vision, recherche et pratique.',
      rolePersonal: 'Usage personnel', rolePersonalLead: 'Conversation, planification, mÃ©moire et aide quotidienne.',
      roleCreative: 'Projets crÃ©atifs', roleCreativeLead: 'Ã‰criture, idÃ©es, dÃ©couverte musicale et mÃ©dias.',
      roleWork: 'Travail et productivitÃ©', roleWorkLead: 'Organisation, brouillons, dÃ©cisions et tÃ¢ches.',
      roleAccess: 'Support dâ€™accessibilitÃ©', roleAccessLead: 'Rythme lisible, moins de mouvement, Ã©tapes clavier et besoins liÃ©s.',
      setupCustom: 'Autre chose que Soul devrait comprendre ?', setupAccess: 'Besoins dâ€™accessibilitÃ© ou dâ€™interaction', saveContinue: 'Enregistrer et continuer', cancel: 'Annuler',
      nextConfigure: 'Configurer les rÃ´les', nextAddApps: 'Ajouter une app de confiance', nextMemory: 'Relire la mÃ©moire', nextBackup: 'CrÃ©er une sauvegarde', nextSettings: 'Ouvrir les paramÃ¨tres', nextEntertainment: 'Ouvrir Divertissement', nextDiagnostics: 'Afficher les diagnostics',
      backupTitle: 'Sauvegardes', backupLead: 'CrÃ©ez un instantanÃ© local portable ou restaurez-en un. ChiffrÃ© lorsque Windows le permet.',
      createBackup: 'CrÃ©er une sauvegarde', refreshList: 'Actualiser', restoreBackup: 'Restaurer la sauvegarde', noBackups: 'Pas encore de sauvegarde. CrÃ©ez-en une avant de changer de fournisseur ou de rÃ©initialiser.',
      diagShow: 'Afficher les diagnostics', diagLead: 'InstantanÃ© local de cette installation. Pas une certification de sÃ©curitÃ© ni une garantie de compatibilitÃ©.',
      behaviorSaved: 'Comportement enregistrÃ©. Langue, ton et accessibilitÃ© restent tels quels.',
      dashFocus: 'Focus', dashRoles: 'RÃ´les', dashMemory: 'MÃ©moire', dashApps: 'Apps', dashMedia: 'Divertissement', dashPrivacy: 'Espace', dashBackups: 'Sauvegardes', dashHealth: 'Diagnostics',
      companionTitle: 'Compagnon de lâ€™espace', companionLead: 'RÃ©ponses locales. Les conversations restent sur ce PC. Ctrl+/ pour le focus.',
      companionApps: 'Apps', companionMedia: 'MÃ©dias', companionMemory: 'MÃ©moire', companionLegal: 'Mentions', companionStatus: 'Ã‰tat', companionHelp: 'Aide',
      overlayTitle: 'Overlays de lâ€™espace', overlayLead: 'FenÃªtres flottantes Eidovara pour le chat Soul, la navigation HTTPS et le site Discord. Pas un overlay Discord officiel. Pas dâ€™injection dans dâ€™autres jeux. Assist ne reÃ§oit pas de jetons Discord.',
      overlayChat: 'Overlay chat Soul', overlayBrowse: 'Overlay navigation', overlayDiscord: 'Discord invitÃ©', overlayGo: 'Ouvrir dans lâ€™overlay navigation', overlayUrlLabel: 'Adresse HTTPS pour lâ€™overlay navigation', overlayKeys: 'Ctrl+Shift+O saute ici. Ctrl+K liste aussi les overlays. Ã‰chap ferme un overlay sauf si vous tapez dans la page invitÃ©e.',
      overlayHelp: 'Les overlays sont des fenÃªtres Eidovara. Discord est leur site dans une session invitÃ©e isolÃ©e â€” pas un overlay officiel, pas dâ€™affiliation, pas dâ€™injection dans dâ€™autres jeux. Assist ne reÃ§oit jamais de jetons Discord ni le DOM invitÃ©.',
      playDeskTitle: 'Bureau Play', playDeskLead: 'RÃ©cents dâ€™apps lancÃ©es avec confirmation, overlays Eidovara, et CPU/mÃ©moire de ce processus. Pas un overlay Steam, pas de tÃ©lÃ©mÃ©trie dâ€™autres jeux.',
      playRecentsEmpty: 'Lancez avec confirmation une app liÃ©e pour la voir ici. Eidovara nâ€™inspecte pas dâ€™autres jeux.',
      overlayRecentsEmpty: 'Les pages HTTPS ouvertes dans lâ€™overlay navigation apparaissent ici. Local seulement.',
      overlayMetricsRefresh: 'Actualiser les mÃ©triques du processus Eidovara', overlayMetricsOff: 'MÃ©triques de processus indisponibles dans cette session.',
      shortcutOverlays: 'Aller aux overlays (chat, navigation, Discord invitÃ©). Dans lâ€™app seulement.',
      companionAskLabel: 'Demander au compagnon de lâ€™espace', companionNote: 'Local uniquement Â· pas un chat cloud Â· Assist nâ€™est pas Soul Â· pas de paiements en direct',
      companionEmptyTitle: 'Demandez Ã  cet espace.', companionEmpty: 'RÃ©ponses locales Ã  partir des faits produit et de votre profil sur lâ€™appareil. Rien nâ€™est envoyÃ© Ã  lâ€™assistant du site ni Ã  Worker /v1/assist.',
      companionSoulOn: 'Soul est un modÃ¨le logiciel sur cet appareil â€” pas une affirmation de conscience.',
      companionSoulOff: 'La configuration Soul facultative est dÃ©sactivÃ©e. Ce compagnon nâ€™est pas Soul et nâ€™est pas conscient.',
      companionOffline: 'Local uniquement. Les conversations restent sur ce PC. Service non attachÃ©.',
      companionServiceDown: 'Local uniquement. Le service attachÃ© est injoignable ; lâ€™espace continue de fonctionner.',
      companionServiceIdle: 'Conversations locales. Le service est santÃ©/Ã©tat seulement â€” le chat nâ€™est pas envoyÃ©.',
      companionThinking: 'Traitement localâ€¦',
      notConfigured: 'non configurÃ©', offlineFirst: 'dâ€™abord hors ligne', connectedProvider: 'fournisseur connectÃ©',
      mediaDisabled: 'La lecture multimÃ©dia est dÃ©sactivÃ©e dans le comportement de Soul.', mediaConfirm: 'Lire ce mÃ©dia dans Eidovara :',
      launchApp: 'Lancer', launchCancelled: 'Lancement annulÃ©.',
      premiumLocked: 'Gratuit : modÃ¨les locaux, Wikipedia/Wikimedia, 3 apps max. RGB, clÃ© Brave et endpoints distants restent Premium.',
      premiumUnlocked: 'Portes Premium de test actives : endpoints distants, clÃ© Brave, RGB et apps illimitÃ©es.',
      soulDockTitle: 'Soul', soulLive: 'Soul est actif sur cet appareil', soulIdle: 'Noyau Soul inactif',
      companionTitle: 'Compagnon Soul', companionLead: 'Noyau de session toujours disponible sur ce PC. Logiciel, pas une personne. Assist nâ€™est pas Soul.',
      companionEmpty: 'Demandez depuis ce panneau. Le noyau local rÃ©pond sur ce PC. Assist nâ€™est pas Soul.',
      companionNote: 'Noyau local Â· Assist nâ€™est pas Soul Â· pas de paiements live Â· voix Windows',
      companionAskLabel: 'Demander Ã  Soul', presenceCaption: 'PrÃ©sence dÃ©corative â€” pas une figure consciente.',
      companionResearchNote: 'Consultation publique aprÃ¨s votre demande â€” pas un index de tout internet.',
      confirmOpenLink: 'Ouvrir cette page HTTPS dans le navigateur ?',
      researchNav: 'Recherche',
      researchTitle: 'Recherche',
      researchLead: 'Consultation web publique aprÃ¨s votre demande. Pas un index de tout internet. Wikipedia/Wikimedia, Internet Archive, recherche optionnelle avec clÃ©, pages que vous ouvrez, et liens YouTube/Spotify/Archive.',
      researchCopy: 'Consultation web publique aprÃ¨s votre demande. Pas un index de tout internet. Wikipedia/Wikimedia, Internet Archive, recherche optionnelle avec clÃ©, pages que vous ouvrez, et liens YouTube/Spotify/Archive.',
      researchEmptyTitle: 'Pas encore de recherche', researchEmpty: 'Demandez une recherche internet sur un sujet, ou une URL HTTPS aprÃ¨s une demande explicite. Ce nâ€™est pas un crawl de tout internet.',
      researchIdle: 'pas encore de recherche', researchResults: 'RÃ©sultats internet', openInBrowser: 'Ouvrir dans le navigateur',
      researchLookup: 'Consulter', researchTopicLabel: 'Sujet ou page HTTPS', dashResearch: 'Recherche', nextResearch: 'Ouvrir Recherche',
      handoffNote: 'Recherche HTTPS officielle dans le navigateur. Eidovara ne rÃ©cupÃ¨re pas le HTML de ce site et ne capture pas les identifiants.',
      sessionLibrary: 'BibliothÃ¨que locale de cette session', discoveryTitle: 'BibliothÃ¨que locale et recherches officielles',
      emptyLibrary: 'Ouvrez un fichier audio ou vidÃ©o local pour le lire dans Eidovara. Les chemins ne sont pas stockÃ©s dans le goÃ»t.',
      emptyDiscovery: 'Demandez de la musique, une vidÃ©o ou un mix dâ€™humeur pour voir les correspondances locales et les puces YouTube/Spotify/Archive.',
      playInEidovara: 'Lire dans Eidovara', playLocal: 'Lire', localNow: 'cet appareil',
      researchIssue: 'ProblÃ¨me de recherche internet :', modelIssue: 'ProblÃ¨me de connexion au modÃ¨le :',
      paletteTitle: 'Aller dans Eidovara', paletteLead: 'Saut et recherche locaux. Pas de crawler. Les apps liÃ©es restent confirmÃ©es. Assist nâ€™est pas Soul.', paletteOpen: 'Aller (Ctrl+K)', paletteHint: 'â†‘â†“ pour dÃ©placer Â· EntrÃ©e pour lancer Â· Ã‰chap pour fermer Â· Ctrl+K', paletteEmpty: 'Aucune correspondance locale. La recherche reste sur cet appareil.',
      cheatsheetTitle: 'Raccourcis clavier', cheatsheetLead: 'Raccourcis Eidovara. Ce calque reste dans lâ€™app â€” pas dâ€™injection dans les jeux ou dâ€™autres processus.', cheatsheetOpen: 'Raccourcis',
      recentsTitle: 'RÃ©cents', recentsLead: 'Apps lancÃ©es avec confirmation, titres de mÃ©dias locaux et souvenirs â€” sur cet appareil seulement.', recentsEmpty: 'Rien de rÃ©cent.',
      notifyTitle: 'Avis dans lâ€™app', notifyLead: 'Ã‰vÃ©nements locaux de cet espace. Pas de toasts OS ni de tÃ©lÃ©mÃ©trie.', notifyClear: 'Effacer', notifyEmpty: 'Aucun avis.',
      sleepTimer: 'Minuteur sommeil', sleepOff: 'Off', sleep15: '15 min', sleep30: '30 min', sleep60: '60 min',
      nowPlaying: 'Lecture en cours', trayStay: 'Rester dans la zone de notification', alwaysOnTop: 'Garder la fenÃªtre au premier plan', openAtLogin: 'Ouvrir Ã  la connexion Windows', pinCompanion: 'Ã‰pingler le compagnon', chromeHelp: 'Zone de notification, premier plan et ouverture Ã  la connexion sâ€™appliquent uniquement Ã  Eidovara.',
      focusQuiet: 'Session concentrÃ©e', focusQuietNote: 'Minuteur local. Les autres apps ne sont ni fermÃ©es ni injectÃ©es.', focusStart: 'DÃ©marrer 25 minutes', focusStop: 'ArrÃªter',
      scratchTitle: 'Brouillon', scratchHint: 'Reste sur cet appareil', scratchPlaceholder: 'Capture rapide. Reste sur cet appareil.', scratchCapture: 'Capturer dans MÃ©moire',
      pinWidget: 'Ã‰pingler une tuile', unpinWidget: 'Retirer',      welcomeTitle: 'Vous y Ãªtes. Commencez par le tableau de bord.', welcomeLead: 'Eidovara est cet espace Windows. Soul (Ã  droite) est lâ€™assistant local â€” un modÃ¨le logiciel, pas un esprit. Assist est facultatif et reste dÃ©sactivÃ© tant que vous ne lâ€™activez pas.',
      welcomeDashboard: 'Ouvrir le tableau de bord', settingsTitle: 'ParamÃ¨tres', settingsLead: 'GroupÃ©s par ce que vous changez. Soul reste sur cet appareil. Assist reste dÃ©sactivÃ© tant que vous ne lâ€™activez pas. Pas de paiement en direct.',
      startPathTitle: 'Commencez ici', startPathLead: 'Un chemin unique aprÃ¨s la confirmation 18+. Vous pouvez masquer cette carte.',
      startPathStep1: 'Ce tableau de bord est lâ€™accueil. Les cartes ouvrent les vrais Ã©crans.',
      startPathStep2: 'Soul (panneau droit) est le modÃ¨le logiciel local. Demandez-lui ici. Ce nâ€™est pas une personne ni lâ€™aide du site.',
      startPathStep3: 'Assist est une aide Worker facultative. Elle reste dÃ©sactivÃ©e tant que vous ne lâ€™activez pas dans ParamÃ¨tres. Assist nâ€™est pas Soul.',
      startTalk: 'Parler Ã  Soul', startApps: 'Ajouter une app de confiance', startSettings: 'Ouvrir ParamÃ¨tres', startDismiss: 'Masquer ce guide',
      paletteEmpty: 'Aucun lieu correspondant. Essayez tableau de bord ou paramÃ¨tres.',
      paletteTitle: 'Aller dans Eidovara', scratchTitle: 'Brouillon', scratchHint: 'Reste sur cet appareil', scratchCapture: 'Capturer vers MÃ©moire', scratchPlaceholder: 'Capture rapide. Reste sur cet appareil.',
      focusQuiet: 'Session de focus', focusStart: 'DÃ©marrer 25 minutes', focusStop: 'ArrÃªter', pinWidget: 'Ã‰pingler une tuile', unpinWidget: 'DÃ©tacher',
      companionPanelTitle: 'Compagnon de lâ€™espace'
    },
    de: {
      newConversation: 'ï¼‹ Neue Unterhaltung', dashboard: 'Ãœbersicht', apps: 'Apps und Gaming', entertainment: 'Unterhaltung', memory: 'Erinnerungen', identity: 'IdentitÃ¤t', settings: 'Einstellungen', language: 'OberflÃ¤chensprache', save: 'Einstellungen speichern',
      adultConfirm: 'VolljÃ¤hrigkeit bestÃ¤tigen', adultEnable: 'Adult Soul aktivieren',
      adultWarning: 'Adult Soul ist nur fÃ¼r Personen bestimmt, die an ihrem Aufenthaltsort volljÃ¤hrig sind. MinderjÃ¤hrige dÃ¼rfen die Funktion nicht verwenden. Diese lokale BestÃ¤tigung ist keine unabhÃ¤ngige IdentitÃ¤ts- oder AltersprÃ¼fung. BestÃ¤tigen Sie, dass Sie volljÃ¤hrig sind, um fortzufahren.',
      dashboardTitle: 'Ihr Eidovara-Arbeitsbereich', dashboardLead: 'Apps, Gaming, Medien, Recherche, Sicherungen und ein lokaler Begleiter, der diese FlÃ¤chen Ã¶ffnet. Optionales Soul ist ein Software-Selbstmodell â€” kein Bewusstsein, nicht der Website-Helfer.',
      appsTitle: 'Apps- und Gaming-Hub', appsLead: 'Ordnen Sie vertrauenswÃ¼rdige Windows-Anwendungen und lassen Sie Windows sie starten. KompatibilitÃ¤t variiert; Eidovara injiziert oder steuert sie nicht.',
      discoverApps: 'Installierte Apps finden', chooseFile: 'ï¼‹ Datei wÃ¤hlen', gamingMode: 'Spielemodus', gamingModeLead: 'Reduziert Eidovaras Licht und Transparenz wÃ¤hrend des Spielens. Ã„ndert nicht den Prozess oder die FPS eines anderen Spiels.', lowOverhead: 'Low-Overhead-Modus',
      entertainmentTitle: 'Unterhaltung', entertainmentLead: 'Lokaler Geschmack, Warteschlangen-Helfer und rechtmÃ¤ÃŸige Ãœbergabe â€” Spotify, YouTube und Internet Archive bleiben offizielle HTTPS-Suchen.',
      emptyAppsTitle: 'Noch keine Anwendungen verknÃ¼pft', emptyAppsBody: 'Bauen Sie ein Windows-Regal aus Titeln, die Sie nutzen dÃ¼rfen.',
      emptyAppsStep1: 'StartmenÃ¼-VerknÃ¼pfungen finden oder eine .exe / .lnk wÃ¤hlen.', emptyAppsStep2: 'Start nur nach BestÃ¤tigung. Eidovara injiziert keine Spiele und umgeht kein Anti-Cheat.', emptyAppsStep3: 'Free behÃ¤lt bis zu drei Apps; Premium-Tests kÃ¶nnen das lokal anheben.',
      emptyFavorites: 'Favoriten erscheinen, sobald Sie im Player ein Herz setzen.', emptyRecent: 'Wiedergabe, Ãœberspringen und Abschluss erscheinen hier. Lokale Pfade stehen nicht in den Geschmacksdaten.', emptyMemory: 'Noch keine dauerhaften Erinnerungen.',
      focusSession: 'Fokus-Sitzung', gamingStream: 'Gaming & Stream', study: 'Lernen', create: 'Gestalten', research: 'Recherche', reviewMemory: 'Erinnerungen prÃ¼fen',
      moodMix: 'Stimmungsmix', fromFavorites: 'Aus Favoriten', watchSomething: 'Etwas ansehen', gamingSoundtrack: 'Gaming-Soundtrack', studySoundtrack: 'Lern-Soundtrack', surpriseMe: 'Ãœberrasche mich',
      favoriteMedia: 'Lieblingsmedien', recentActivity: 'Letzte AktivitÃ¤t', mixHelper: 'Warteschlangen-Hilfe', mixEmpty: 'Spielen oder favorisieren Sie etwas fÃ¼r einen lokalen Mix. VorschlÃ¤ge bleiben auf diesem GerÃ¤t.',
      platformTitle: 'Plattformverbindungen', platformLead: 'Spotify, YouTube und Internet Archive Ã¶ffnen offizielle Suchen im Systembrowser. Eidovara erfasst keine Zugangsdaten, umgeht keine Abos, lÃ¤dt keine geschÃ¼tzten Streams, injiziert keine anderen Player und impliziert keine Partnerschaft.',
      openLocalMedia: 'Lokale Medien Ã¶ffnen',
      setupTitle: 'WofÃ¼r brauchen Sie Soul?', setupLead: 'WÃ¤hlen Sie passende Rollen. SpÃ¤ter unter Einstellungen Ã¤nderbar.',
      roleGaming: 'Gaming- und Schnitt-Assistenz', roleGamingLead: 'Spielplanung, Clips, kreativer Schnitt und AblÃ¤ufe.',
      roleStream: 'Stream-Hilfe', roleStreamLead: 'Ziele, OBS-Vorbereitung, Szenen und Checklisten. Direkte OBS-Steuerung ist nicht in dieser Version.',
      roleStudy: 'Lernassistenz', roleStudyLead: 'ErklÃ¤rungen, WiederholungsplÃ¤ne, Recherche und Ãœbung.',
      rolePersonal: 'PersÃ¶nliche Nutzung', rolePersonalLead: 'GesprÃ¤ch, Planung, Speicher und Alltagshilfe.',
      roleCreative: 'Kreative Projekte', roleCreativeLead: 'Schreiben, Ideen, Musikentdeckung und Medien.',
      roleWork: 'Arbeit und ProduktivitÃ¤t', roleWorkLead: 'Organisation, EntwÃ¼rfe, Entscheidungen und Aufgaben.',
      roleAccess: 'Barrierefreiheit', roleAccessLead: 'Lesbares Tempo, weniger Bewegung, tastaturklare Schritte und verwandte BedÃ¼rfnisse.',
      setupCustom: 'Was soll Soul sonst noch verstehen?', setupAccess: 'Barrierefreiheit oder Interaktionsbedarf', saveContinue: 'Speichern und weiter', cancel: 'Abbrechen',
      nextConfigure: 'Rollen einrichten', nextAddApps: 'VertrauenswÃ¼rdige App hinzufÃ¼gen', nextMemory: 'Erinnerungen prÃ¼fen', nextBackup: 'Sicherung erstellen', nextSettings: 'Einstellungen Ã¶ffnen', nextEntertainment: 'Unterhaltung Ã¶ffnen', nextDiagnostics: 'Diagnose zeigen',
      backupTitle: 'Sicherungen', backupLead: 'Erstellen Sie eine lokale Momentaufnahme oder stellen Sie eine frÃ¼here wieder her. VerschlÃ¼sselt, wenn Windows-Schutz verfÃ¼gbar ist.',
      createBackup: 'Sicherung erstellen', refreshList: 'Liste aktualisieren', restoreBackup: 'AusgewÃ¤hlte Sicherung wiederherstellen', noBackups: 'Noch keine Sicherungen. Erstellen Sie eine, bevor Sie Anbieter wechseln oder zurÃ¼cksetzen.',
      diagShow: 'Diagnose anzeigen', diagLead: 'Lokale Momentaufnahme dieser Installation. Keine Sicherheitszertifizierung und keine KompatibilitÃ¤tsgarantie.',
      behaviorSaved: 'Verhalten gespeichert. Sprache, Ton und Barrierefreiheit bleiben erhalten.',
      dashFocus: 'Fokus', dashRoles: 'Rollen', dashMemory: 'Speicher', dashApps: 'Apps', dashMedia: 'Unterhaltung', dashPrivacy: 'Arbeitsbereich', dashBackups: 'Sicherungen', dashHealth: 'Diagnose',
      companionTitle: 'Arbeitsbereich-Begleiter', companionLead: 'Lokale Antworten. GesprÃ¤che bleiben auf diesem PC. Strg+/ zum Fokus.',
      companionApps: 'Apps', companionMedia: 'Medien', companionMemory: 'Speicher', companionLegal: 'Rechtliches', companionStatus: 'Status', companionHelp: 'Hilfe',
      overlayTitle: 'Workspace-Overlays', overlayLead: 'Schwebende Eidovara-Fenster fÃ¼r Soul-Chat, HTTPS-Browsing und Discords eigene Website. Kein offizielles Discord-Overlay. Keine Injektion in andere Spiele. Assist erhÃ¤lt keine Discord-Tokens.',
      overlayChat: 'Soul-Chat-Overlay', overlayBrowse: 'Browse-Overlay', overlayDiscord: 'Discord-Gast', overlayGo: 'Im Browse-Overlay Ã¶ffnen', overlayUrlLabel: 'HTTPS-Adresse fÃ¼r das Browse-Overlay', overlayKeys: 'Strg+Umschalt+O springt hierher. Strg+K listet Overlays ebenfalls. Esc schlieÃŸt ein Overlay, auÃŸer Sie tippen in der Gastseite.',
      overlayHelp: 'Overlays sind Eidovara-Fenster. Discord ist deren Website in einer isolierten Gastsitzung â€” kein offizielles Discord-Overlay, keine Affiliation, keine Injektion in andere Spiele. Assist erhÃ¤lt keine Discord-Tokens und kein Gast-DOM.',
      playDeskTitle: 'Play-Pult', playDeskLead: 'Zuletzt bestÃ¤tigt gestartete Apps, Eidovara-Overlays und CPU/Speicher dieses Prozesses. Kein Steam-Overlay und keine Telemetrie anderer Spiele.',
      playRecentsEmpty: 'Starten Sie eine verknÃ¼pfte App mit BestÃ¤tigung, damit sie hier erscheint. Eidovara liest keine anderen Spiele.',
      overlayRecentsEmpty: 'HTTPS-Seiten, die Sie im Browse-Overlay Ã¶ffnen, erscheinen hier. Nur lokal.',
      overlayMetricsRefresh: 'Eidovara-Prozessmetriken aktualisieren', overlayMetricsOff: 'Prozessmetriken in dieser Sitzung nicht verfÃ¼gbar.',
      shortcutOverlays: 'Zu Workspace-Overlays springen (Chat, Browse, Discord-Gast). Nur in der App.',
      companionAskLabel: 'Den Arbeitsbereich-Begleiter fragen', companionNote: 'Nur lokal Â· kein Cloud-Chat Â· Assist ist nicht Soul Â· keine Live-Zahlungen',
      companionEmptyTitle: 'Fragen Sie diesen Arbeitsbereich.', companionEmpty: 'Lokale Antworten aus Produktfakten und Ihrem Profil auf dem GerÃ¤t. Nichts geht an den Website-Helfer oder Worker /v1/assist.',
      companionSoulOn: 'Soul ist ein Software-Selbstmodell auf diesem GerÃ¤t â€” kein Bewusstseinsanspruch.',
      companionSoulOff: 'Optionales Soul-Setup ist aus. Dieser Begleiter ist nicht Soul und nicht bewusst.',
      companionOffline: 'Nur lokal. GesprÃ¤che bleiben auf diesem PC. Kein Dienst verbunden.',
      companionServiceDown: 'Nur lokal. Verbundener Dienst unerreichbar; der Arbeitsbereich lÃ¤uft weiter.',
      companionServiceIdle: 'Lokale GesprÃ¤che. Der Dienst ist nur Health/Status â€” Chat wird nicht gesendet.',
      companionThinking: 'Lokal beschÃ¤ftigtâ€¦',
      notConfigured: 'nicht konfiguriert', offlineFirst: 'zuerst offline', connectedProvider: 'verbundener Anbieter',
      mediaDisabled: 'Medienwiedergabe ist in den Soul-Verhaltenseinstellungen deaktiviert.', mediaConfirm: 'Dieses Medium in Eidovara wiedergeben:',
      launchApp: 'Starten', launchCancelled: 'Start abgebrochen.',
      premiumLocked: 'Free: lokale Modelle, Wikipedia/Wikimedia, bis zu 3 Apps. RGB, Brave-SchlÃ¼ssel und Remote-Endpunkte bleiben Premium.',
      premiumUnlocked: 'Premium-Test aktiv: Remote-Endpunkte, Brave-SchlÃ¼ssel, RGB und unbegrenzte Apps.',
      soulDockTitle: 'Soul', soulLive: 'Soul ist auf diesem PC aktiv', soulIdle: 'Soul-Kernel inaktiv',
      companionTitle: 'Soul-Begleiter', companionLead: 'Sitzungs-Kernel immer auf diesem PC. Software, keine Person. Assist ist nicht Soul.',
      companionEmpty: 'Fragen Sie Ã¼ber dieses Dock. Der lokale Kernel antwortet auf diesem PC. Assist ist nicht Soul.',
      companionNote: 'Lokaler Kernel Â· Assist ist nicht Soul Â· keine Live-Zahlungen Â· Windows-Stimmen',
      companionAskLabel: 'Soul fragen', presenceCaption: 'Dekorative PrÃ¤senz â€” keine bewusste Figur.',
      companionResearchNote: 'Ã–ffentliche Suche nach Ihrer Bitte â€” kein Gesamtindex des Internets.',
      confirmOpenLink: 'Diese HTTPS-Seite im Browser Ã¶ffnen?',
      researchNav: 'Recherche',
      researchTitle: 'Recherche',
      researchLead: 'Ã–ffentliche Websuche nach Ihrer Bitte. Kein Gesamtindex des Internets. Wikipedia/Wikimedia, Internet Archive, optionale SchlÃ¼sselsuche, geÃ¶ffnete Seiten und offizielle YouTube/Spotify/Archive-Links.',
      researchCopy: 'Ã–ffentliche Websuche nach Ihrer Bitte. Kein Gesamtindex des Internets. Wikipedia/Wikimedia, Internet Archive, optionale SchlÃ¼sselsuche, geÃ¶ffnete Seiten und offizielle YouTube/Spotify/Archive-Links.',
      researchEmptyTitle: 'Noch keine Suche', researchEmpty: 'Bitten Sie um eine Internetsuche zu einem Thema oder um eine HTTPS-URL nach expliziter Anfrage. Das ist kein Crawl des ganzen Internets.',
      researchIdle: 'noch keine Suche', researchResults: 'Internetergebnisse', openInBrowser: 'Im Browser Ã¶ffnen',
      researchLookup: 'Nachschlagen', researchTopicLabel: 'Thema oder HTTPS-Seite', dashResearch: 'Recherche', nextResearch: 'Recherche Ã¶ffnen',
      handoffNote: 'Offizielle HTTPS-Suche im Browser. Eidovara lÃ¤dt das HTML dieser Seite nicht und erfasst keine Anmeldungen.',
      sessionLibrary: 'Lokale Bibliothek dieser Sitzung', discoveryTitle: 'Lokale Bibliothek und offizielle Suchen',
      emptyLibrary: 'Ã–ffnen Sie eine lokale Audio- oder Videodatei zur Wiedergabe in Eidovara. Pfade stehen nicht in den Geschmacksdaten.',
      emptyDiscovery: 'Bitten Sie um Musik, etwas zum Ansehen oder einen Stimmungsmix, um lokale Treffer und YouTube/Spotify/Archive-Chips zu sehen.',
      playInEidovara: 'In Eidovara wiedergeben', playLocal: 'Wiedergeben', localNow: 'dieses GerÃ¤t',
      researchIssue: 'Internetsuche-Problem:', modelIssue: 'Modellverbindungsproblem:',
      paletteTitle: 'Springen in Eidovara', paletteLead: 'Lokaler Sprung und Suche. Kein Crawler. VerknÃ¼pfte Apps starten weiter nur nach BestÃ¤tigung. Assist ist nicht Soul.', paletteOpen: 'Springen (Ctrl+K)', paletteHint: 'â†‘â†“ bewegen Â· Enter ausfÃ¼hren Â· Esc schlieÃŸen Â· Ctrl+K', paletteEmpty: 'Keine lokalen Treffer. Suche bleibt auf diesem PC.',
      cheatsheetTitle: 'TastaturÃ¼bersicht', cheatsheetLead: 'Eidovara-TastenkÃ¼rzel. Diese Ãœberlagerung bleibt in der App â€” keine Injektion in Spiele oder andere Prozesse.', cheatsheetOpen: 'KÃ¼rzel',
      recentsTitle: 'Zuletzt', recentsLead: 'BestÃ¤tigt gestartete Apps, lokale Medientitel und Erinnerungen â€” nur auf diesem PC.', recentsEmpty: 'Noch nichts zuletzt.',
      notifyTitle: 'In-App-Hinweise', notifyLead: 'Lokale Ereignisse dieses Arbeitsbereichs. Kein OS-Spam und keine Telemetrie.', notifyClear: 'Leeren', notifyEmpty: 'Noch keine Hinweise.',
      sleepTimer: 'Schlaf-Timer', sleepOff: 'Aus', sleep15: '15 Min', sleep30: '30 Min', sleep60: '60 Min',
      nowPlaying: 'Gerade lÃ¤uft', trayStay: 'Im Infobereich weiterlaufen', alwaysOnTop: 'Fenster im Vordergrund', openAtLogin: 'Bei Windows-Anmeldung Ã¶ffnen', pinCompanion: 'Begleiter anheften', chromeHelp: 'Infobereich, Immer im Vordergrund und Anmeldung gelten nur fÃ¼r dieses Eidovara-Fenster.',
      focusQuiet: 'Fokus-Sitzung', focusQuietNote: 'Lokaler Timer. Andere Apps werden nicht geschlossen oder injiziert.', focusStart: '25 Minuten starten', focusStop: 'Stopp',
      scratchTitle: 'Notizblock', scratchHint: 'Bleibt auf diesem PC', scratchPlaceholder: 'Schnellerfassung. Bleibt auf diesem GerÃ¤t.', scratchCapture: 'In Speicher Ã¼bernehmen',
      pinWidget: 'Kachel anheften', unpinWidget: 'LÃ¶sen',      welcomeTitle: 'Sie sind drin. Starten Sie in der Ãœbersicht.', welcomeLead: 'Eidovara ist dieser Windows-Arbeitsbereich. Soul (rechts) ist der lokale Assistent â€” ein Software-Selbstmodell, kein Geist. Assist ist optional und bleibt aus, bis Sie ihn einschalten.',
      welcomeDashboard: 'Ãœbersicht Ã¶ffnen', settingsTitle: 'Einstellungen', settingsLead: 'Gruppiert nach dem, was Sie Ã¤ndern. Soul bleibt auf diesem PC. Assist bleibt aus, bis Sie ihn einschalten. Keine Live-Zahlungen.',
      startPathTitle: 'Hier starten', startPathLead: 'Ein klarer Weg nach der 18+-BestÃ¤tigung. Diese Karte kÃ¶nnen Sie ausblenden.',
      startPathStep1: 'Diese Ãœbersicht ist die Startseite. Die Karten Ã¶ffnen die echten FlÃ¤chen.',
      startPathStep2: 'Soul (rechtes Dock) ist das lokale Software-Selbstmodell. Fragen Sie hier. Keine Person und nicht der Website-Helfer.',
      startPathStep3: 'Assist ist ein optionaler Worker-Helfer. Er bleibt aus, bis Sie ihn in den Einstellungen einschalten. Assist ist nicht Soul.',
      startTalk: 'Mit Soul sprechen', startApps: 'VertrauenswÃ¼rdige App hinzufÃ¼gen', startSettings: 'Einstellungen Ã¶ffnen', startDismiss: 'Diese Anleitung ausblenden',
      paletteEmpty: 'Kein Treffer. Versuchen Sie Ãœbersicht oder Einstellungen.',
      paletteTitle: 'Springen in Eidovara', scratchTitle: 'Notizblock', scratchHint: 'Bleibt auf diesem PC', scratchCapture: 'In den Speicher erfassen', scratchPlaceholder: 'Schnelle Notiz. Bleibt auf diesem GerÃ¤t.',
      focusQuiet: 'Fokus-Sitzung', focusStart: '25 Minuten starten', focusStop: 'Stopp', pinWidget: 'Kachel anheften', unpinWidget: 'LÃ¶sen',
      companionPanelTitle: 'Arbeitsbereich-Begleiter'
    }
  };
  let locale = 'en';
  const t = (key, fallback) => messages[locale]?.[key] || messages.en[key] || fallback || key;
  const set = value => {
    locale = messages[value] ? value : 'en';
    document.documentElement.lang = locale;
    for (const node of document.querySelectorAll('[data-i18n]')) node.textContent = t(node.dataset.i18n, node.textContent);
    window.dispatchEvent(new CustomEvent('eidovara:locale', { detail: { locale } }));
  };
  window.eidovaraI18n = { set, t, supported: Object.keys(messages), messages };
  queueMicrotask(async () => {
    try {
      let settings = await window.soul.getSettings();
      const select = document.querySelector('#languageSelect');
      if (!select) return;
      select.value = messages[settings.language] ? settings.language : 'en';
      set(select.value);
      select.addEventListener('change', async () => {
        set(select.value);
        settings = await window.soul.saveSettings({ provider: settings.provider, endpoint: settings.endpoint, model: settings.model, language: select.value, theme: settings.theme, companion: settings.companion });
        const state = await window.soul.snapshot();
        const p = state.assistant?.preferences || {}, c = state.assistant?.capabilities || {};
        await window.soul.configureAssistant({ autonomy: state.assistant?.autonomy, initiativeEnabled: state.assistant?.initiativeEnabled, reflectionEnabled: state.assistant?.reflectionEnabled, responseLength: p.responseLength, tone: p.tone, focusMode: p.focusMode, accessibility: p.accessibility, language: select.value, webResearch: c.webResearch, mediaPlayback: c.mediaPlayback, memoryLearning: c.memoryLearning });
      });
    } catch {}
  });
})();

