// SPDX-FileCopyrightText: 2026 Tyler Michael Bosworth
// SPDX-License-Identifier: LicenseRef-Eidovara-Source-Available-1.0
(() => {
  const messages = {
    en: {
      newConversation: '＋ New conversation', dashboard: 'Dashboard', apps: 'Apps & Gaming', entertainment: 'Entertainment', memory: 'Memory', identity: 'Identity', settings: 'Settings', language: 'Interface language', save: 'Save settings',
      adultConfirm: 'Confirm legal-adult status', adultEnable: 'Enable Adult Soul',
      adultWarning: 'Adult Soul is only for people who have reached the age of majority where they are located. It must not be used by minors. This local confirmation is not independent identity or age verification. Confirm that you are legally an adult to continue.',
      dashboardTitle: 'Your Eidovara workspace', dashboardLead: 'Apps, gaming, media, research, backups, and a local companion that can open those surfaces. Optional Soul is a software self-model — not consciousness, not the website helper.',
      appsTitle: 'Apps & Gaming Hub', appsLead: 'Organize trusted Windows applications and ask Windows to launch them. Compatibility varies; Eidovara does not inject into or control them.',
      discoverApps: 'Discover installed apps', chooseFile: '＋ Choose file', gamingMode: 'Gaming mode', gamingModeLead: 'Reduces Eidovara’s animated lighting and transparency while you play. It does not change another game’s process or frame rate.', lowOverhead: 'Low-overhead mode',
      entertainmentTitle: 'Entertainment', entertainmentLead: 'Local taste, queue helpers, and lawful platform handoff — Spotify, YouTube, and Internet Archive stay official HTTPS searches.',
      emptyAppsTitle: 'No applications linked yet', emptyAppsBody: 'Build a Windows shelf of titles you already trust and are permitted to use.',
      emptyAppsStep1: 'Discover Start Menu shortcuts on this PC, or choose a .exe / .lnk file.', emptyAppsStep2: 'Launch is confirmation-only. Eidovara does not inject into games or bypass anti-cheat.', emptyAppsStep3: 'Free editions keep up to three linked apps; Premium testing can raise that locally.',
      emptyFavorites: 'Favorite media will appear here after you heart something in the player.', emptyRecent: 'Play, skip, and complete events will appear here. Local file paths are not stored in taste records.', emptyMemory: 'No durable memories yet.',
      focusSession: 'Focus session', gamingStream: 'Gaming & stream', study: 'Study', create: 'Create', research: 'Research', reviewMemory: 'Review memory',
      moodMix: 'Mood mix', fromFavorites: 'From favorites', watchSomething: 'Watch something', gamingSoundtrack: 'Gaming soundtrack', studySoundtrack: 'Study soundtrack', surpriseMe: 'Surprise me',
      favoriteMedia: 'Favorite media', recentActivity: 'Recent activity', mixHelper: 'Queue helper', mixEmpty: 'Play or favorite something to grow a local mix. Suggestions stay on this device.',
      platformTitle: 'Platform connections', platformLead: 'Spotify, YouTube, and Internet Archive open official searches in your system browser. Eidovara does not capture credentials, bypass subscriptions, download protected streams, inject into other players, or imply affiliation.',
      openLocalMedia: 'Open local media',
      setupTitle: 'What do you need Soul for?', setupLead: 'Choose any roles that fit. You can change this later in Settings.',
      roleGaming: 'Gaming & editing assistant', roleGamingLead: 'Game planning, clips, creative editing, and workflows.',
      roleStream: 'Stream helper', roleStreamLead: 'Streaming goals, OBS preparation, scenes, inputs, and checklists. Direct OBS control is not in this release.',
      roleStudy: 'Studying assistant', roleStudyLead: 'Explanations, review plans, research, and practice.',
      rolePersonal: 'Personal usage', rolePersonalLead: 'Conversation, planning, memory, and everyday assistance.',
      roleCreative: 'Creative projects', roleCreativeLead: 'Writing, ideas, music discovery, and media.',
      roleWork: 'Work & productivity', roleWorkLead: 'Organization, drafting, decisions, and task support.',
      roleAccess: 'Accessibility support', roleAccessLead: 'Readable pacing, reduced motion, keyboard-first steps, and related workspace needs.',
      setupCustom: 'Anything else Soul should understand?', setupAccess: 'Accessibility or interaction needs', saveContinue: 'Save and continue', cancel: 'Cancel',
      nextConfigure: 'Configure roles', nextAddApps: 'Add a trusted app', nextMemory: 'Review memory', nextBackup: 'Create a backup', nextSettings: 'Open settings', nextEntertainment: 'Open Entertainment', nextDiagnostics: 'Show diagnostics',
      backupTitle: 'Backups', backupLead: 'Create a portable local snapshot or restore an earlier snapshot. Encrypted when Windows protection is available.',
      createBackup: 'Create backup', refreshList: 'Refresh list', restoreBackup: 'Restore selected backup', noBackups: 'No backups yet. Create one before changing providers or resetting.',
      diagShow: 'Show diagnostics', diagLead: 'Local snapshot of this installation. Not a security certification or compatibility guarantee.',
      behaviorSaved: 'Behavior settings saved. Language, tone, and accessibility remain as set.',
      dashFocus: 'Focus', dashRoles: 'Roles', dashMemory: 'Memory', dashApps: 'Apps', dashMedia: 'Entertainment', dashPrivacy: 'Workspace', dashBackups: 'Backups', dashHealth: 'Diagnostics',
      companionTitle: 'Workspace companion', companionLead: 'Local answers. Conversations stay on this PC. Ctrl+/ to focus.',
      companionApps: 'Apps', companionMedia: 'Media', companionMemory: 'Memory', companionLegal: 'Legal', companionStatus: 'Status', companionHelp: 'Help',
      companionAskLabel: 'Ask the workspace companion', companionNote: 'Local only · not a cloud chat · Assist is not Soul · no live payments',
      companionEmptyTitle: 'Ask this workspace.', companionEmpty: 'Local answers from product facts and your on-device profile. Nothing is sent to the website helper or Worker /v1/assist.',
      companionSoulOn: 'Soul is a software self-model on this device — not a claim of consciousness.',
      companionSoulOff: 'Optional Soul setup is off. This companion is not Soul and is not conscious.',
      companionOffline: 'Local-only. Conversations stay on this PC. Service not attached.',
      companionServiceDown: 'Local-only. Attached service is unreachable; the workspace still works.',
      companionServiceIdle: 'Local conversations. Service is health/status only — chat is not sent.',
      companionThinking: 'Working locally…',
      notConfigured: 'not configured', offlineFirst: 'offline-first', connectedProvider: 'connected provider',
      mediaDisabled: 'Media playback is disabled in Soul behavior settings.', mediaConfirm: 'Play this media in Eidovara:',
      launchApp: 'Launch', launchCancelled: 'Launch cancelled.',
      premiumLocked: 'Free: offline/local models, Wikipedia/Wikimedia research, up to 3 apps. RGB, Brave key, and remote endpoints stay Premium.',
      premiumUnlocked: 'Premium test gates are on: remote endpoints, Brave search key, RGB, and unlimited apps.',
      soulDockTitle: 'Soul', soulLive: 'Soul is live on this PC', soulIdle: 'Soul kernel idle',
      companionTitle: 'Soul companion', companionLead: 'Always-on session kernel on this PC. Software, not a person. Assist is not Soul.',
      companionEmpty: 'Ask from this dock. Local kernel answers on this PC. Assist is not Soul.',
      companionNote: 'Local kernel · Assist is not Soul · no live payments · voices from Windows',
      companionAskLabel: 'Ask Soul', presenceCaption: 'Decorative presence — not a conscious figure.',
      companionResearchNote: 'Public lookup after you asked — not a full-internet index.',
      confirmOpenLink: 'Open this HTTPS page in your browser?',
      researchTitle: 'Research', researchLead: 'Public web lookup after you ask. Not a full-internet index. Wikipedia/Wikimedia, Internet Archive, optional keyed search, pages you open, plus official YouTube/Spotify/Archive search links. Local files play in Eidovara.',
      researchNav: 'Research',
      researchCopy: 'Public web lookup after you ask. Not a full-internet index. Wikipedia/Wikimedia, Internet Archive, optional keyed search, pages you open, plus official YouTube/Spotify/Archive search links. Local files play in Eidovara.',
      researchEmptyTitle: 'No lookup yet', researchEmpty: 'Ask me to search the internet for a topic, or include an HTTPS URL after an explicit internet/web/online request. This is not a crawl of the whole internet.',
      researchIdle: 'no lookup yet', researchResults: 'Internet results', openInBrowser: 'Open in browser',
      researchLookup: 'Look up', researchTopicLabel: 'Topic or HTTPS page', dashResearch: 'Research', nextResearch: 'Open Research',
      handoffNote: 'Official HTTPS search in your browser. Eidovara does not fetch that site’s HTML or capture logins.',
      sessionLibrary: 'This session’s local library', discoveryTitle: 'Local library & official searches',
      emptyLibrary: 'Open a local audio or video file to play it in Eidovara. Paths stay out of taste records.',
      emptyDiscovery: 'Ask for music, a watch, or a mood mix to show local matches and official YouTube/Spotify/Archive search chips.',
      playInEidovara: 'Play in Eidovara', playLocal: 'Play', localNow: 'this device',
      researchIssue: 'Internet search issue:', modelIssue: 'Model connection issue:',
      paletteTitle: 'Jump in Eidovara', paletteLead: 'Local jump and search. No background crawler. Linked apps still confirm-launch. Assist is not Soul.', paletteOpen: 'Jump (Ctrl+K)', paletteHint: '↑↓ to move · Enter to run · Esc to close · Ctrl+K', paletteEmpty: 'No local matches. Search stays on this PC.',
      cheatsheetTitle: 'Keyboard cheatsheet', cheatsheetLead: 'Eidovara shortcuts. This overlay is in-app only — it does not inject into games or other processes.', cheatsheetOpen: 'Shortcuts',
      focusQuiet: 'Focus session', focusQuietNote: 'Local timer. Other apps are not closed or injected into.', focusStart: 'Start 25 minutes', focusStop: 'Stop',
      scratchTitle: 'Scratchpad', scratchHint: 'Stays on this PC', scratchPlaceholder: 'Quick capture. Stays on this device.', scratchCapture: 'Capture to Memory',
      pinWidget: 'Pin a tile', unpinWidget: 'Unpin',      welcomeTitle: 'You\'re in. Start on the Dashboard.', welcomeLead: 'Eidovara is this Windows workspace. Soul (right side) is the local assistant — a software self-model, not a mind. Assist is an optional Worker helper and stays off until you turn it on. They are not the same thing.',
      welcomeDashboard: 'Open Dashboard', settingsTitle: 'Settings', settingsLead: 'Grouped by what you change. Soul stays on this PC. Assist stays off unless you turn it on. No live payments.',
      startPathTitle: 'Start here', startPathLead: 'One path after you confirm 18+. You can hide this card anytime.',
      startPathStep1: 'This Dashboard is home. Cards below open the real surfaces.',
      startPathStep2: 'Soul (right dock) is the local software self-model. Ask it here. It is not a person and not the website helper.',
      startPathStep3: 'Assist is an optional Worker helper. It stays off unless you enable it in Settings. Assist is not Soul.',
      startTalk: 'Talk with Soul', startApps: 'Add a trusted app', startSettings: 'Open Settings', startDismiss: 'Hide this guide',
      paletteEmpty: 'No matching places. Try dashboard or settings.',
      paletteTitle: 'Jump in Eidovara', scratchTitle: 'Scratchpad', scratchHint: 'Stays on this PC', scratchCapture: 'Capture to Memory', scratchPlaceholder: 'Quick capture. Stays on this device.',
      focusQuiet: 'Focus session', focusStart: 'Start 25 minutes', focusStop: 'Stop', pinWidget: 'Pin a tile', unpinWidget: 'Unpin',
      companionPanelTitle: 'Workspace companion'
    },
    es: {
      newConversation: '＋ Nueva conversación', dashboard: 'Panel', apps: 'Aplicaciones y juegos', entertainment: 'Entretenimiento', memory: 'Memoria', identity: 'Identidad', settings: 'Configuración', language: 'Idioma de la interfaz', save: 'Guardar configuración',
      adultConfirm: 'Confirmar mayoría de edad legal', adultEnable: 'Activar Soul para adultos',
      adultWarning: 'Soul para adultos es solo para personas que hayan alcanzado la mayoría de edad donde se encuentren. Los menores no deben usarlo. Esta confirmación local no verifica de forma independiente la identidad ni la edad. Confirma que eres legalmente adulto para continuar.',
      dashboardTitle: 'Tu espacio Eidovara', dashboardLead: 'Apps, juegos, medios, investigación, copias y un compañero local que abre esas superficies. Soul opcional es un modelo de software, no consciencia ni el asistente del sitio.',
      appsTitle: 'Centro de aplicaciones y juegos', appsLead: 'Organiza aplicaciones de Windows de confianza y pide a Windows que las abra. La compatibilidad varía; Eidovara no inyecta ni las controla.',
      discoverApps: 'Descubrir apps instaladas', chooseFile: '＋ Elegir archivo', gamingMode: 'Modo de juego', gamingModeLead: 'Reduce la iluminación y transparencia de Eidovara mientras juegas. No cambia el proceso ni los FPS de otro juego.', lowOverhead: 'Modo de bajo consumo',
      entertainmentTitle: 'Entretenimiento', entertainmentLead: 'Gusto local, ayudas de cola y transferencia lícita: Spotify, YouTube e Internet Archive siguen siendo búsquedas HTTPS oficiales.',
      emptyAppsTitle: 'Aún no hay aplicaciones vinculadas', emptyAppsBody: 'Arma un estante de Windows con títulos que ya confías y puedes usar.',
      emptyAppsStep1: 'Descubre accesos del menú Inicio, o elige un archivo .exe / .lnk.', emptyAppsStep2: 'El lanzamiento es solo con confirmación. Eidovara no inyecta juegos ni evade anti-cheat.', emptyAppsStep3: 'La edición gratuita permite hasta tres apps; Premium de prueba puede subir ese límite en local.',
      emptyFavorites: 'Los favoritos aparecerán cuando marques algo en el reproductor.', emptyRecent: 'Reproducciones, omisiones y cierres aparecerán aquí. Las rutas locales no se guardan en el gusto.', emptyMemory: 'Aún no hay recuerdos duraderos.',
      focusSession: 'Sesión de enfoque', gamingStream: 'Juegos y stream', study: 'Estudio', create: 'Crear', research: 'Investigar', reviewMemory: 'Revisar memoria',
      moodMix: 'Mezcla de ánimo', fromFavorites: 'Desde favoritos', watchSomething: 'Ver algo', gamingSoundtrack: 'Banda de juego', studySoundtrack: 'Banda de estudio', surpriseMe: 'Sorpréndeme',
      favoriteMedia: 'Medios favoritos', recentActivity: 'Actividad reciente', mixHelper: 'Ayuda de cola', mixEmpty: 'Reproduce o marca un favorito para armar una mezcla local. Las sugerencias se quedan en este dispositivo.',
      platformTitle: 'Conexiones de plataforma', platformLead: 'Spotify, YouTube e Internet Archive abren búsquedas oficiales en el navegador. Eidovara no captura credenciales, evita suscripciones, descarga streams protegidos, inyecta otros reproductores ni implica afiliación.',
      openLocalMedia: 'Abrir medio local',
      setupTitle: '¿Para qué necesitas a Soul?', setupLead: 'Elige los roles que encajen. Puedes cambiarlos luego en Configuración.',
      roleGaming: 'Asistente de juegos y edición', roleGamingLead: 'Plan de partidas, clips, edición creativa y flujos.',
      roleStream: 'Ayuda de streaming', roleStreamLead: 'Objetivos, preparación de OBS, escenas y listas. El control directo de OBS no está en esta versión.',
      roleStudy: 'Asistente de estudio', roleStudyLead: 'Explicaciones, planes de repaso, investigación y práctica.',
      rolePersonal: 'Uso personal', rolePersonalLead: 'Conversación, planificación, memoria y ayuda cotidiana.',
      roleCreative: 'Proyectos creativos', roleCreativeLead: 'Escritura, ideas, descubrimiento musical y medios.',
      roleWork: 'Trabajo y productividad', roleWorkLead: 'Organización, borradores, decisiones y tareas.',
      roleAccess: 'Apoyo de accesibilidad', roleAccessLead: 'Ritmo legible, menos movimiento, pasos con teclado y necesidades afines.',
      setupCustom: '¿Algo más que Soul deba entender?', setupAccess: 'Necesidades de accesibilidad o interacción', saveContinue: 'Guardar y continuar', cancel: 'Cancelar',
      nextConfigure: 'Configurar roles', nextAddApps: 'Añadir app de confianza', nextMemory: 'Revisar memoria', nextBackup: 'Crear copia', nextSettings: 'Abrir configuración', nextEntertainment: 'Abrir Entretenimiento', nextDiagnostics: 'Ver diagnósticos',
      backupTitle: 'Copias de seguridad', backupLead: 'Crea una instantánea local o restaura una anterior. Cifrada cuando Windows lo permite.',
      createBackup: 'Crear copia', refreshList: 'Actualizar lista', restoreBackup: 'Restaurar copia seleccionada', noBackups: 'Aún no hay copias. Crea una antes de cambiar de proveedor o restablecer.',
      diagShow: 'Mostrar diagnósticos', diagLead: 'Instantánea local de esta instalación. No es una certificación de seguridad ni una garantía de compatibilidad.',
      behaviorSaved: 'Comportamiento guardado. Idioma, tono y accesibilidad se mantienen.',
      dashFocus: 'Enfoque', dashRoles: 'Roles', dashMemory: 'Memoria', dashApps: 'Apps', dashMedia: 'Entretenimiento', dashPrivacy: 'Espacio', dashBackups: 'Copias', dashHealth: 'Diagnóstico',
      companionTitle: 'Compañero del espacio', companionLead: 'Respuestas locales. Las conversaciones quedan en este PC. Ctrl+/ para enfocar.',
      companionApps: 'Apps', companionMedia: 'Medios', companionMemory: 'Memoria', companionLegal: 'Legal', companionStatus: 'Estado', companionHelp: 'Ayuda',
      companionAskLabel: 'Preguntar al compañero del espacio', companionNote: 'Solo local · no es chat en la nube · Assist no es Soul · sin pagos en vivo',
      companionEmptyTitle: 'Pregunta a este espacio.', companionEmpty: 'Respuestas locales con hechos del producto y tu perfil en el dispositivo. Nada se envía al asistente del sitio ni a Worker /v1/assist.',
      companionSoulOn: 'Soul es un modelo de software en este dispositivo, no una afirmación de consciencia.',
      companionSoulOff: 'La configuración opcional de Soul está apagada. Este compañero no es Soul y no es consciente.',
      companionOffline: 'Solo local. Las conversaciones quedan en este PC. Servicio no conectado.',
      companionServiceDown: 'Solo local. El servicio conectado no responde; el espacio sigue funcionando.',
      companionServiceIdle: 'Conversaciones locales. El servicio es solo salud/estado: el chat no se envía.',
      companionThinking: 'Trabajando en local…',
      notConfigured: 'sin configurar', offlineFirst: 'primero local', connectedProvider: 'proveedor conectado',
      mediaDisabled: 'La reproducción está desactivada en el comportamiento de Soul.', mediaConfirm: 'Reproducir este medio en Eidovara:',
      launchApp: 'Abrir', launchCancelled: 'Lanzamiento cancelado.',
      premiumLocked: 'Gratis: modelos locales, Wikipedia/Wikimedia, hasta 3 apps. RGB, clave Brave y endpoints remotos son Premium.',
      premiumUnlocked: 'Prueba Premium activa: endpoints remotos, clave Brave, RGB y apps ilimitadas.',
      soulDockTitle: 'Soul', soulLive: 'Soul está en vivo en este PC', soulIdle: 'Kernel de Soul inactivo',
      companionTitle: 'Compañero Soul', companionLead: 'Núcleo de sesión siempre disponible en este PC. Software, no una persona. Assist no es Soul.',
      companionEmpty: 'Pregunta desde este panel. El núcleo local responde en este PC. Assist no es Soul.',
      companionNote: 'Núcleo local · Assist no es Soul · sin pagos en vivo · voces de Windows',
      companionAskLabel: 'Preguntar a Soul', presenceCaption: 'Presencia decorativa: no es una figura consciente.',
      companionResearchNote: 'Consulta pública después de que lo pediste — no es un índice de todo internet.',
      confirmOpenLink: '¿Abrir esta página HTTPS en el navegador?',
      researchNav: 'Investigar',
      researchTitle: 'Investigación',
      researchLead: 'Consulta web pública cuando lo pides. No es un índice de todo internet. Wikipedia/Wikimedia, Internet Archive, búsqueda con clave opcional, páginas que abres y enlaces oficiales de YouTube/Spotify/Archive.',
      researchCopy: 'Consulta web pública cuando lo pides. No es un índice de todo internet. Wikipedia/Wikimedia, Internet Archive, búsqueda con clave opcional, páginas que abres y enlaces oficiales de YouTube/Spotify/Archive.',
      researchEmptyTitle: 'Aún no hay consulta', researchEmpty: 'Pídeme buscar en internet un tema, o incluye una URL HTTPS tras una petición explícita. Esto no rastrea todo internet.',
      researchIdle: 'sin consulta', researchResults: 'Resultados de internet', openInBrowser: 'Abrir en el navegador',
      researchLookup: 'Consultar', researchTopicLabel: 'Tema o página HTTPS', dashResearch: 'Investigación', nextResearch: 'Abrir Investigación',
      handoffNote: 'Búsqueda HTTPS oficial en el navegador. Eidovara no descarga el HTML de ese sitio ni captura inicios de sesión.',
      sessionLibrary: 'Biblioteca local de esta sesión', discoveryTitle: 'Biblioteca local y búsquedas oficiales',
      emptyLibrary: 'Abre un audio o video local para reproducirlo en Eidovara. Las rutas no se guardan en el gusto.',
      emptyDiscovery: 'Pide música, algo para ver o una mezcla de ánimo para ver coincidencias locales y chips de YouTube/Spotify/Archive.',
      playInEidovara: 'Reproducir en Eidovara', playLocal: 'Reproducir', localNow: 'este dispositivo',
      researchIssue: 'Problema de búsqueda en internet:', modelIssue: 'Problema de conexión del modelo:',
      paletteTitle: 'Saltar en Eidovara', paletteLead: 'Salto y búsqueda locales. Sin rastreador. Las apps vinculadas siguen pidiendo confirmación. Assist no es Soul.', paletteOpen: 'Saltar (Ctrl+K)', paletteHint: '↑↓ para mover · Intro para ejecutar · Esc para cerrar · Ctrl+K', paletteEmpty: 'Sin coincidencias locales. La búsqueda se queda en este PC.',
      cheatsheetTitle: 'Atajos de teclado', cheatsheetLead: 'Atajos de Eidovara. Esta capa es solo dentro de la app; no se inyecta en juegos ni otros procesos.', cheatsheetOpen: 'Atajos',
      focusQuiet: 'Sesión de enfoque', focusQuietNote: 'Temporizador local. No se cierran ni inyectan otras apps.', focusStart: 'Empezar 25 minutos', focusStop: 'Parar',
      scratchTitle: 'Bloc', scratchHint: 'Se queda en este PC', scratchPlaceholder: 'Captura rápida. Se queda en este dispositivo.', scratchCapture: 'Capturar a Memoria',
      pinWidget: 'Fijar un mosaico', unpinWidget: 'Quitar',      welcomeTitle: 'Ya estás dentro. Empieza en el Panel.', welcomeLead: 'Eidovara es este espacio de Windows. Soul (derecha) es el asistente local: un modelo de software, no una mente. Assist es un ayudante opcional y permanece apagado hasta que lo actives.',
      welcomeDashboard: 'Abrir Panel', settingsTitle: 'Configuración', settingsLead: 'Agrupado por lo que cambias. Soul se queda en este PC. Assist permanece apagado salvo que lo actives. No hay pagos en vivo.',
      startPathTitle: 'Empieza aquí', startPathLead: 'Un camino claro después de confirmar 18+. Puedes ocultar esta tarjeta.',
      startPathStep1: 'Este Panel es el inicio. Las tarjetas abren las superficies reales.',
      startPathStep2: 'Soul (el muelle derecho) es el modelo de software local. Pregúntale aquí. No es una persona ni el ayudante del sitio.',
      startPathStep3: 'Assist es un ayudante opcional del Worker. Permanece apagado salvo que lo actives en Configuración. Assist no es Soul.',
      startTalk: 'Hablar con Soul', startApps: 'Añadir app de confianza', startSettings: 'Abrir Configuración', startDismiss: 'Ocultar esta guía',
      paletteEmpty: 'Ningún lugar coincide. Prueba panel o configuración.',
      paletteTitle: 'Saltar en Eidovara', scratchTitle: 'Bloc', scratchHint: 'Se queda en este PC', scratchCapture: 'Capturar a Memoria', scratchPlaceholder: 'Captura rápida. Se queda en este dispositivo.',
      focusQuiet: 'Sesión de enfoque', focusStart: 'Empezar 25 minutos', focusStop: 'Parar', pinWidget: 'Fijar mosaico', unpinWidget: 'Quitar',
      companionPanelTitle: 'Compañero del espacio'
    },
    fr: {
      newConversation: '＋ Nouvelle conversation', dashboard: 'Tableau de bord', apps: 'Applications et jeux', entertainment: 'Divertissement', memory: 'Mémoire', identity: 'Identité', settings: 'Paramètres', language: 'Langue de l’interface', save: 'Enregistrer',
      adultConfirm: 'Confirmer la majorité légale', adultEnable: 'Activer Soul adulte',
      adultWarning: 'Soul adulte est réservé aux personnes ayant atteint l’âge de la majorité là où elles se trouvent. Les mineurs ne doivent pas l’utiliser. Cette confirmation locale ne constitue pas une vérification indépendante de l’identité ou de l’âge. Confirmez que vous êtes légalement adulte pour continuer.',
      dashboardTitle: 'Votre espace Eidovara', dashboardLead: 'Apps, jeu, médias, recherche, sauvegardes, et un compagnon local qui ouvre ces surfaces. Soul facultatif est un modèle logiciel — pas la conscience, pas l’assistant du site.',
      appsTitle: 'Hub applications et jeux', appsLead: 'Organisez des applications Windows de confiance et demandez à Windows de les lancer. La compatibilité varie ; Eidovara n’injecte ni ne les contrôle.',
      discoverApps: 'Découvrir les apps installées', chooseFile: '＋ Choisir un fichier', gamingMode: 'Mode jeu', gamingModeLead: 'Réduit l’éclairage et la transparence d’Eidovara pendant que vous jouez. Cela ne change pas le processus ni les FPS d’un autre jeu.', lowOverhead: 'Mode allégé',
      entertainmentTitle: 'Divertissement', entertainmentLead: 'Goût local, aides de file et transfert licite — Spotify, YouTube et Internet Archive restent des recherches HTTPS officielles.',
      emptyAppsTitle: 'Aucune application liée', emptyAppsBody: 'Constituez une étagère Windows de titres que vous avez le droit d’utiliser.',
      emptyAppsStep1: 'Découvrez les raccourcis du menu Démarrer, ou choisissez un .exe / .lnk.', emptyAppsStep2: 'Le lancement est confirmé. Eidovara n’injecte pas les jeux et n’évite pas l’anti-cheat.', emptyAppsStep3: 'L’édition gratuite garde jusqu’à trois apps ; le test Premium peut l’augmenter localement.',
      emptyFavorites: 'Les favoris apparaîtront après un cœur dans le lecteur.', emptyRecent: 'Lectures, ignores et fins apparaîtront ici. Les chemins locaux ne sont pas stockés dans le goût.', emptyMemory: 'Pas encore de souvenirs durables.',
      focusSession: 'Session concentrée', gamingStream: 'Jeu et stream', study: 'Étude', create: 'Créer', research: 'Recherche', reviewMemory: 'Relire la mémoire',
      moodMix: 'Mix d’humeur', fromFavorites: 'Depuis les favoris', watchSomething: 'Regarder', gamingSoundtrack: 'Bande jeu', studySoundtrack: 'Bande étude', surpriseMe: 'Surprenez-moi',
      favoriteMedia: 'Médias favoris', recentActivity: 'Activité récente', mixHelper: 'Aide de file', mixEmpty: 'Lisez ou favoritez un média pour une mixte locale. Les suggestions restent sur cet appareil.',
      platformTitle: 'Connexions de plateformes', platformLead: 'Spotify, YouTube et Internet Archive ouvrent des recherches officielles dans le navigateur. Eidovara ne capture pas les identifiants, n’évite pas les abonnements, ne télécharge pas les flux protégés, n’injecte pas d’autres lecteurs et n’implique aucune affiliation.',
      openLocalMedia: 'Ouvrir un média local',
      setupTitle: 'Pour quoi avez-vous besoin de Soul ?', setupLead: 'Choisissez les rôles adaptés. Modifiable plus tard dans Paramètres.',
      roleGaming: 'Assistant jeu et montage', roleGamingLead: 'Plan de parties, clips, montage créatif et flux.',
      roleStream: 'Aide streaming', roleStreamLead: 'Objectifs, préparation OBS, scènes et listes. Le contrôle direct d’OBS n’est pas dans cette version.',
      roleStudy: 'Assistant d’étude', roleStudyLead: 'Explications, plans de révision, recherche et pratique.',
      rolePersonal: 'Usage personnel', rolePersonalLead: 'Conversation, planification, mémoire et aide quotidienne.',
      roleCreative: 'Projets créatifs', roleCreativeLead: 'Écriture, idées, découverte musicale et médias.',
      roleWork: 'Travail et productivité', roleWorkLead: 'Organisation, brouillons, décisions et tâches.',
      roleAccess: 'Support d’accessibilité', roleAccessLead: 'Rythme lisible, moins de mouvement, étapes clavier et besoins liés.',
      setupCustom: 'Autre chose que Soul devrait comprendre ?', setupAccess: 'Besoins d’accessibilité ou d’interaction', saveContinue: 'Enregistrer et continuer', cancel: 'Annuler',
      nextConfigure: 'Configurer les rôles', nextAddApps: 'Ajouter une app de confiance', nextMemory: 'Relire la mémoire', nextBackup: 'Créer une sauvegarde', nextSettings: 'Ouvrir les paramètres', nextEntertainment: 'Ouvrir Divertissement', nextDiagnostics: 'Afficher les diagnostics',
      backupTitle: 'Sauvegardes', backupLead: 'Créez un instantané local portable ou restaurez-en un. Chiffré lorsque Windows le permet.',
      createBackup: 'Créer une sauvegarde', refreshList: 'Actualiser', restoreBackup: 'Restaurer la sauvegarde', noBackups: 'Pas encore de sauvegarde. Créez-en une avant de changer de fournisseur ou de réinitialiser.',
      diagShow: 'Afficher les diagnostics', diagLead: 'Instantané local de cette installation. Pas une certification de sécurité ni une garantie de compatibilité.',
      behaviorSaved: 'Comportement enregistré. Langue, ton et accessibilité restent tels quels.',
      dashFocus: 'Focus', dashRoles: 'Rôles', dashMemory: 'Mémoire', dashApps: 'Apps', dashMedia: 'Divertissement', dashPrivacy: 'Espace', dashBackups: 'Sauvegardes', dashHealth: 'Diagnostics',
      companionTitle: 'Compagnon de l’espace', companionLead: 'Réponses locales. Les conversations restent sur ce PC. Ctrl+/ pour le focus.',
      companionApps: 'Apps', companionMedia: 'Médias', companionMemory: 'Mémoire', companionLegal: 'Mentions', companionStatus: 'État', companionHelp: 'Aide',
      companionAskLabel: 'Demander au compagnon de l’espace', companionNote: 'Local uniquement · pas un chat cloud · Assist n’est pas Soul · pas de paiements en direct',
      companionEmptyTitle: 'Demandez à cet espace.', companionEmpty: 'Réponses locales à partir des faits produit et de votre profil sur l’appareil. Rien n’est envoyé à l’assistant du site ni à Worker /v1/assist.',
      companionSoulOn: 'Soul est un modèle logiciel sur cet appareil — pas une affirmation de conscience.',
      companionSoulOff: 'La configuration Soul facultative est désactivée. Ce compagnon n’est pas Soul et n’est pas conscient.',
      companionOffline: 'Local uniquement. Les conversations restent sur ce PC. Service non attaché.',
      companionServiceDown: 'Local uniquement. Le service attaché est injoignable ; l’espace continue de fonctionner.',
      companionServiceIdle: 'Conversations locales. Le service est santé/état seulement — le chat n’est pas envoyé.',
      companionThinking: 'Traitement local…',
      notConfigured: 'non configuré', offlineFirst: 'd’abord hors ligne', connectedProvider: 'fournisseur connecté',
      mediaDisabled: 'La lecture multimédia est désactivée dans le comportement de Soul.', mediaConfirm: 'Lire ce média dans Eidovara :',
      launchApp: 'Lancer', launchCancelled: 'Lancement annulé.',
      premiumLocked: 'Gratuit : modèles locaux, Wikipedia/Wikimedia, 3 apps max. RGB, clé Brave et endpoints distants restent Premium.',
      premiumUnlocked: 'Portes Premium de test actives : endpoints distants, clé Brave, RGB et apps illimitées.',
      soulDockTitle: 'Soul', soulLive: 'Soul est actif sur cet appareil', soulIdle: 'Noyau Soul inactif',
      companionTitle: 'Compagnon Soul', companionLead: 'Noyau de session toujours disponible sur ce PC. Logiciel, pas une personne. Assist n’est pas Soul.',
      companionEmpty: 'Demandez depuis ce panneau. Le noyau local répond sur ce PC. Assist n’est pas Soul.',
      companionNote: 'Noyau local · Assist n’est pas Soul · pas de paiements live · voix Windows',
      companionAskLabel: 'Demander à Soul', presenceCaption: 'Présence décorative — pas une figure consciente.',
      companionResearchNote: 'Consultation publique après votre demande — pas un index de tout internet.',
      confirmOpenLink: 'Ouvrir cette page HTTPS dans le navigateur ?',
      researchNav: 'Recherche',
      researchTitle: 'Recherche',
      researchLead: 'Consultation web publique après votre demande. Pas un index de tout internet. Wikipedia/Wikimedia, Internet Archive, recherche optionnelle avec clé, pages que vous ouvrez, et liens YouTube/Spotify/Archive.',
      researchCopy: 'Consultation web publique après votre demande. Pas un index de tout internet. Wikipedia/Wikimedia, Internet Archive, recherche optionnelle avec clé, pages que vous ouvrez, et liens YouTube/Spotify/Archive.',
      researchEmptyTitle: 'Pas encore de recherche', researchEmpty: 'Demandez une recherche internet sur un sujet, ou une URL HTTPS après une demande explicite. Ce n’est pas un crawl de tout internet.',
      researchIdle: 'pas encore de recherche', researchResults: 'Résultats internet', openInBrowser: 'Ouvrir dans le navigateur',
      researchLookup: 'Consulter', researchTopicLabel: 'Sujet ou page HTTPS', dashResearch: 'Recherche', nextResearch: 'Ouvrir Recherche',
      handoffNote: 'Recherche HTTPS officielle dans le navigateur. Eidovara ne récupère pas le HTML de ce site et ne capture pas les identifiants.',
      sessionLibrary: 'Bibliothèque locale de cette session', discoveryTitle: 'Bibliothèque locale et recherches officielles',
      emptyLibrary: 'Ouvrez un fichier audio ou vidéo local pour le lire dans Eidovara. Les chemins ne sont pas stockés dans le goût.',
      emptyDiscovery: 'Demandez de la musique, une vidéo ou un mix d’humeur pour voir les correspondances locales et les puces YouTube/Spotify/Archive.',
      playInEidovara: 'Lire dans Eidovara', playLocal: 'Lire', localNow: 'cet appareil',
      researchIssue: 'Problème de recherche internet :', modelIssue: 'Problème de connexion au modèle :',
      paletteTitle: 'Aller dans Eidovara', paletteLead: 'Saut et recherche locaux. Pas de crawler. Les apps liées restent confirmées. Assist n’est pas Soul.', paletteOpen: 'Aller (Ctrl+K)', paletteHint: '↑↓ pour déplacer · Entrée pour lancer · Échap pour fermer · Ctrl+K', paletteEmpty: 'Aucune correspondance locale. La recherche reste sur cet appareil.',
      cheatsheetTitle: 'Raccourcis clavier', cheatsheetLead: 'Raccourcis Eidovara. Ce calque reste dans l’app — pas d’injection dans les jeux ou d’autres processus.', cheatsheetOpen: 'Raccourcis',
      focusQuiet: 'Session concentrée', focusQuietNote: 'Minuteur local. Les autres apps ne sont ni fermées ni injectées.', focusStart: 'Démarrer 25 minutes', focusStop: 'Arrêter',
      scratchTitle: 'Brouillon', scratchHint: 'Reste sur cet appareil', scratchPlaceholder: 'Capture rapide. Reste sur cet appareil.', scratchCapture: 'Capturer dans Mémoire',
      pinWidget: 'Épingler une tuile', unpinWidget: 'Retirer',      welcomeTitle: 'Vous y êtes. Commencez par le tableau de bord.', welcomeLead: 'Eidovara est cet espace Windows. Soul (à droite) est l’assistant local — un modèle logiciel, pas un esprit. Assist est facultatif et reste désactivé tant que vous ne l’activez pas.',
      welcomeDashboard: 'Ouvrir le tableau de bord', settingsTitle: 'Paramètres', settingsLead: 'Groupés par ce que vous changez. Soul reste sur cet appareil. Assist reste désactivé tant que vous ne l’activez pas. Pas de paiement en direct.',
      startPathTitle: 'Commencez ici', startPathLead: 'Un chemin unique après la confirmation 18+. Vous pouvez masquer cette carte.',
      startPathStep1: 'Ce tableau de bord est l’accueil. Les cartes ouvrent les vrais écrans.',
      startPathStep2: 'Soul (panneau droit) est le modèle logiciel local. Demandez-lui ici. Ce n’est pas une personne ni l’aide du site.',
      startPathStep3: 'Assist est une aide Worker facultative. Elle reste désactivée tant que vous ne l’activez pas dans Paramètres. Assist n’est pas Soul.',
      startTalk: 'Parler à Soul', startApps: 'Ajouter une app de confiance', startSettings: 'Ouvrir Paramètres', startDismiss: 'Masquer ce guide',
      paletteEmpty: 'Aucun lieu correspondant. Essayez tableau de bord ou paramètres.',
      paletteTitle: 'Aller dans Eidovara', scratchTitle: 'Brouillon', scratchHint: 'Reste sur cet appareil', scratchCapture: 'Capturer vers Mémoire', scratchPlaceholder: 'Capture rapide. Reste sur cet appareil.',
      focusQuiet: 'Session de focus', focusStart: 'Démarrer 25 minutes', focusStop: 'Arrêter', pinWidget: 'Épingler une tuile', unpinWidget: 'Détacher',
      companionPanelTitle: 'Compagnon de l’espace'
    },
    de: {
      newConversation: '＋ Neue Unterhaltung', dashboard: 'Übersicht', apps: 'Apps und Gaming', entertainment: 'Unterhaltung', memory: 'Erinnerungen', identity: 'Identität', settings: 'Einstellungen', language: 'Oberflächensprache', save: 'Einstellungen speichern',
      adultConfirm: 'Volljährigkeit bestätigen', adultEnable: 'Adult Soul aktivieren',
      adultWarning: 'Adult Soul ist nur für Personen bestimmt, die an ihrem Aufenthaltsort volljährig sind. Minderjährige dürfen die Funktion nicht verwenden. Diese lokale Bestätigung ist keine unabhängige Identitäts- oder Altersprüfung. Bestätigen Sie, dass Sie volljährig sind, um fortzufahren.',
      dashboardTitle: 'Ihr Eidovara-Arbeitsbereich', dashboardLead: 'Apps, Gaming, Medien, Recherche, Sicherungen und ein lokaler Begleiter, der diese Flächen öffnet. Optionales Soul ist ein Software-Selbstmodell — kein Bewusstsein, nicht der Website-Helfer.',
      appsTitle: 'Apps- und Gaming-Hub', appsLead: 'Ordnen Sie vertrauenswürdige Windows-Anwendungen und lassen Sie Windows sie starten. Kompatibilität variiert; Eidovara injiziert oder steuert sie nicht.',
      discoverApps: 'Installierte Apps finden', chooseFile: '＋ Datei wählen', gamingMode: 'Spielemodus', gamingModeLead: 'Reduziert Eidovaras Licht und Transparenz während des Spielens. Ändert nicht den Prozess oder die FPS eines anderen Spiels.', lowOverhead: 'Low-Overhead-Modus',
      entertainmentTitle: 'Unterhaltung', entertainmentLead: 'Lokaler Geschmack, Warteschlangen-Helfer und rechtmäßige Übergabe — Spotify, YouTube und Internet Archive bleiben offizielle HTTPS-Suchen.',
      emptyAppsTitle: 'Noch keine Anwendungen verknüpft', emptyAppsBody: 'Bauen Sie ein Windows-Regal aus Titeln, die Sie nutzen dürfen.',
      emptyAppsStep1: 'Startmenü-Verknüpfungen finden oder eine .exe / .lnk wählen.', emptyAppsStep2: 'Start nur nach Bestätigung. Eidovara injiziert keine Spiele und umgeht kein Anti-Cheat.', emptyAppsStep3: 'Free behält bis zu drei Apps; Premium-Tests können das lokal anheben.',
      emptyFavorites: 'Favoriten erscheinen, sobald Sie im Player ein Herz setzen.', emptyRecent: 'Wiedergabe, Überspringen und Abschluss erscheinen hier. Lokale Pfade stehen nicht in den Geschmacksdaten.', emptyMemory: 'Noch keine dauerhaften Erinnerungen.',
      focusSession: 'Fokus-Sitzung', gamingStream: 'Gaming & Stream', study: 'Lernen', create: 'Gestalten', research: 'Recherche', reviewMemory: 'Erinnerungen prüfen',
      moodMix: 'Stimmungsmix', fromFavorites: 'Aus Favoriten', watchSomething: 'Etwas ansehen', gamingSoundtrack: 'Gaming-Soundtrack', studySoundtrack: 'Lern-Soundtrack', surpriseMe: 'Überrasche mich',
      favoriteMedia: 'Lieblingsmedien', recentActivity: 'Letzte Aktivität', mixHelper: 'Warteschlangen-Hilfe', mixEmpty: 'Spielen oder favorisieren Sie etwas für einen lokalen Mix. Vorschläge bleiben auf diesem Gerät.',
      platformTitle: 'Plattformverbindungen', platformLead: 'Spotify, YouTube und Internet Archive öffnen offizielle Suchen im Systembrowser. Eidovara erfasst keine Zugangsdaten, umgeht keine Abos, lädt keine geschützten Streams, injiziert keine anderen Player und impliziert keine Partnerschaft.',
      openLocalMedia: 'Lokale Medien öffnen',
      setupTitle: 'Wofür brauchen Sie Soul?', setupLead: 'Wählen Sie passende Rollen. Später unter Einstellungen änderbar.',
      roleGaming: 'Gaming- und Schnitt-Assistenz', roleGamingLead: 'Spielplanung, Clips, kreativer Schnitt und Abläufe.',
      roleStream: 'Stream-Hilfe', roleStreamLead: 'Ziele, OBS-Vorbereitung, Szenen und Checklisten. Direkte OBS-Steuerung ist nicht in dieser Version.',
      roleStudy: 'Lernassistenz', roleStudyLead: 'Erklärungen, Wiederholungspläne, Recherche und Übung.',
      rolePersonal: 'Persönliche Nutzung', rolePersonalLead: 'Gespräch, Planung, Speicher und Alltagshilfe.',
      roleCreative: 'Kreative Projekte', roleCreativeLead: 'Schreiben, Ideen, Musikentdeckung und Medien.',
      roleWork: 'Arbeit und Produktivität', roleWorkLead: 'Organisation, Entwürfe, Entscheidungen und Aufgaben.',
      roleAccess: 'Barrierefreiheit', roleAccessLead: 'Lesbares Tempo, weniger Bewegung, tastaturklare Schritte und verwandte Bedürfnisse.',
      setupCustom: 'Was soll Soul sonst noch verstehen?', setupAccess: 'Barrierefreiheit oder Interaktionsbedarf', saveContinue: 'Speichern und weiter', cancel: 'Abbrechen',
      nextConfigure: 'Rollen einrichten', nextAddApps: 'Vertrauenswürdige App hinzufügen', nextMemory: 'Erinnerungen prüfen', nextBackup: 'Sicherung erstellen', nextSettings: 'Einstellungen öffnen', nextEntertainment: 'Unterhaltung öffnen', nextDiagnostics: 'Diagnose zeigen',
      backupTitle: 'Sicherungen', backupLead: 'Erstellen Sie eine lokale Momentaufnahme oder stellen Sie eine frühere wieder her. Verschlüsselt, wenn Windows-Schutz verfügbar ist.',
      createBackup: 'Sicherung erstellen', refreshList: 'Liste aktualisieren', restoreBackup: 'Ausgewählte Sicherung wiederherstellen', noBackups: 'Noch keine Sicherungen. Erstellen Sie eine, bevor Sie Anbieter wechseln oder zurücksetzen.',
      diagShow: 'Diagnose anzeigen', diagLead: 'Lokale Momentaufnahme dieser Installation. Keine Sicherheitszertifizierung und keine Kompatibilitätsgarantie.',
      behaviorSaved: 'Verhalten gespeichert. Sprache, Ton und Barrierefreiheit bleiben erhalten.',
      dashFocus: 'Fokus', dashRoles: 'Rollen', dashMemory: 'Speicher', dashApps: 'Apps', dashMedia: 'Unterhaltung', dashPrivacy: 'Arbeitsbereich', dashBackups: 'Sicherungen', dashHealth: 'Diagnose',
      companionTitle: 'Arbeitsbereich-Begleiter', companionLead: 'Lokale Antworten. Gespräche bleiben auf diesem PC. Strg+/ zum Fokus.',
      companionApps: 'Apps', companionMedia: 'Medien', companionMemory: 'Speicher', companionLegal: 'Rechtliches', companionStatus: 'Status', companionHelp: 'Hilfe',
      companionAskLabel: 'Den Arbeitsbereich-Begleiter fragen', companionNote: 'Nur lokal · kein Cloud-Chat · Assist ist nicht Soul · keine Live-Zahlungen',
      companionEmptyTitle: 'Fragen Sie diesen Arbeitsbereich.', companionEmpty: 'Lokale Antworten aus Produktfakten und Ihrem Profil auf dem Gerät. Nichts geht an den Website-Helfer oder Worker /v1/assist.',
      companionSoulOn: 'Soul ist ein Software-Selbstmodell auf diesem Gerät — kein Bewusstseinsanspruch.',
      companionSoulOff: 'Optionales Soul-Setup ist aus. Dieser Begleiter ist nicht Soul und nicht bewusst.',
      companionOffline: 'Nur lokal. Gespräche bleiben auf diesem PC. Kein Dienst verbunden.',
      companionServiceDown: 'Nur lokal. Verbundener Dienst unerreichbar; der Arbeitsbereich läuft weiter.',
      companionServiceIdle: 'Lokale Gespräche. Der Dienst ist nur Health/Status — Chat wird nicht gesendet.',
      companionThinking: 'Lokal beschäftigt…',
      notConfigured: 'nicht konfiguriert', offlineFirst: 'zuerst offline', connectedProvider: 'verbundener Anbieter',
      mediaDisabled: 'Medienwiedergabe ist in den Soul-Verhaltenseinstellungen deaktiviert.', mediaConfirm: 'Dieses Medium in Eidovara wiedergeben:',
      launchApp: 'Starten', launchCancelled: 'Start abgebrochen.',
      premiumLocked: 'Free: lokale Modelle, Wikipedia/Wikimedia, bis zu 3 Apps. RGB, Brave-Schlüssel und Remote-Endpunkte bleiben Premium.',
      premiumUnlocked: 'Premium-Test aktiv: Remote-Endpunkte, Brave-Schlüssel, RGB und unbegrenzte Apps.',
      soulDockTitle: 'Soul', soulLive: 'Soul ist auf diesem PC aktiv', soulIdle: 'Soul-Kernel inaktiv',
      companionTitle: 'Soul-Begleiter', companionLead: 'Sitzungs-Kernel immer auf diesem PC. Software, keine Person. Assist ist nicht Soul.',
      companionEmpty: 'Fragen Sie über dieses Dock. Der lokale Kernel antwortet auf diesem PC. Assist ist nicht Soul.',
      companionNote: 'Lokaler Kernel · Assist ist nicht Soul · keine Live-Zahlungen · Windows-Stimmen',
      companionAskLabel: 'Soul fragen', presenceCaption: 'Dekorative Präsenz — keine bewusste Figur.',
      companionResearchNote: 'Öffentliche Suche nach Ihrer Bitte — kein Gesamtindex des Internets.',
      confirmOpenLink: 'Diese HTTPS-Seite im Browser öffnen?',
      researchNav: 'Recherche',
      researchTitle: 'Recherche',
      researchLead: 'Öffentliche Websuche nach Ihrer Bitte. Kein Gesamtindex des Internets. Wikipedia/Wikimedia, Internet Archive, optionale Schlüsselsuche, geöffnete Seiten und offizielle YouTube/Spotify/Archive-Links.',
      researchCopy: 'Öffentliche Websuche nach Ihrer Bitte. Kein Gesamtindex des Internets. Wikipedia/Wikimedia, Internet Archive, optionale Schlüsselsuche, geöffnete Seiten und offizielle YouTube/Spotify/Archive-Links.',
      researchEmptyTitle: 'Noch keine Suche', researchEmpty: 'Bitten Sie um eine Internetsuche zu einem Thema oder um eine HTTPS-URL nach expliziter Anfrage. Das ist kein Crawl des ganzen Internets.',
      researchIdle: 'noch keine Suche', researchResults: 'Internetergebnisse', openInBrowser: 'Im Browser öffnen',
      researchLookup: 'Nachschlagen', researchTopicLabel: 'Thema oder HTTPS-Seite', dashResearch: 'Recherche', nextResearch: 'Recherche öffnen',
      handoffNote: 'Offizielle HTTPS-Suche im Browser. Eidovara lädt das HTML dieser Seite nicht und erfasst keine Anmeldungen.',
      sessionLibrary: 'Lokale Bibliothek dieser Sitzung', discoveryTitle: 'Lokale Bibliothek und offizielle Suchen',
      emptyLibrary: 'Öffnen Sie eine lokale Audio- oder Videodatei zur Wiedergabe in Eidovara. Pfade stehen nicht in den Geschmacksdaten.',
      emptyDiscovery: 'Bitten Sie um Musik, etwas zum Ansehen oder einen Stimmungsmix, um lokale Treffer und YouTube/Spotify/Archive-Chips zu sehen.',
      playInEidovara: 'In Eidovara wiedergeben', playLocal: 'Wiedergeben', localNow: 'dieses Gerät',
      researchIssue: 'Internetsuche-Problem:', modelIssue: 'Modellverbindungsproblem:',
      paletteTitle: 'Springen in Eidovara', paletteLead: 'Lokaler Sprung und Suche. Kein Crawler. Verknüpfte Apps starten weiter nur nach Bestätigung. Assist ist nicht Soul.', paletteOpen: 'Springen (Ctrl+K)', paletteHint: '↑↓ bewegen · Enter ausführen · Esc schließen · Ctrl+K', paletteEmpty: 'Keine lokalen Treffer. Suche bleibt auf diesem PC.',
      cheatsheetTitle: 'Tastaturübersicht', cheatsheetLead: 'Eidovara-Tastenkürzel. Diese Überlagerung bleibt in der App — keine Injektion in Spiele oder andere Prozesse.', cheatsheetOpen: 'Kürzel',
      focusQuiet: 'Fokus-Sitzung', focusQuietNote: 'Lokaler Timer. Andere Apps werden nicht geschlossen oder injiziert.', focusStart: '25 Minuten starten', focusStop: 'Stopp',
      scratchTitle: 'Notizblock', scratchHint: 'Bleibt auf diesem PC', scratchPlaceholder: 'Schnellerfassung. Bleibt auf diesem Gerät.', scratchCapture: 'In Speicher übernehmen',
      pinWidget: 'Kachel anheften', unpinWidget: 'Lösen',      welcomeTitle: 'Sie sind drin. Starten Sie in der Übersicht.', welcomeLead: 'Eidovara ist dieser Windows-Arbeitsbereich. Soul (rechts) ist der lokale Assistent — ein Software-Selbstmodell, kein Geist. Assist ist optional und bleibt aus, bis Sie ihn einschalten.',
      welcomeDashboard: 'Übersicht öffnen', settingsTitle: 'Einstellungen', settingsLead: 'Gruppiert nach dem, was Sie ändern. Soul bleibt auf diesem PC. Assist bleibt aus, bis Sie ihn einschalten. Keine Live-Zahlungen.',
      startPathTitle: 'Hier starten', startPathLead: 'Ein klarer Weg nach der 18+-Bestätigung. Diese Karte können Sie ausblenden.',
      startPathStep1: 'Diese Übersicht ist die Startseite. Die Karten öffnen die echten Flächen.',
      startPathStep2: 'Soul (rechtes Dock) ist das lokale Software-Selbstmodell. Fragen Sie hier. Keine Person und nicht der Website-Helfer.',
      startPathStep3: 'Assist ist ein optionaler Worker-Helfer. Er bleibt aus, bis Sie ihn in den Einstellungen einschalten. Assist ist nicht Soul.',
      startTalk: 'Mit Soul sprechen', startApps: 'Vertrauenswürdige App hinzufügen', startSettings: 'Einstellungen öffnen', startDismiss: 'Diese Anleitung ausblenden',
      paletteEmpty: 'Kein Treffer. Versuchen Sie Übersicht oder Einstellungen.',
      paletteTitle: 'Springen in Eidovara', scratchTitle: 'Notizblock', scratchHint: 'Bleibt auf diesem PC', scratchCapture: 'In den Speicher erfassen', scratchPlaceholder: 'Schnelle Notiz. Bleibt auf diesem Gerät.',
      focusQuiet: 'Fokus-Sitzung', focusStart: '25 Minuten starten', focusStop: 'Stopp', pinWidget: 'Kachel anheften', unpinWidget: 'Lösen',
      companionPanelTitle: 'Arbeitsbereich-Begleiter'
    }
  };
  let locale = 'en';
  const t = (key, fallback) => messages[locale]?.[key] || messages.en[key] || fallback || key;
  const set = value => {
    locale = messages[value] ? value : 'en';
    document.documentElement.lang = locale;
    for (const node of document.querySelectorAll('[data-i18n]')) node.textContent = t(node.dataset.i18n, node.textContent);
    window.dispatchEvent(new CustomEvent('eidovara:locale', { detail: { locale } }));
  };
  window.eidovaraI18n = { set, t, supported: Object.keys(messages), messages };
  queueMicrotask(async () => {
    try {
      let settings = await window.soul.getSettings();
      const select = document.querySelector('#languageSelect');
      if (!select) return;
      select.value = messages[settings.language] ? settings.language : 'en';
      set(select.value);
      select.addEventListener('change', async () => {
        set(select.value);
        settings = await window.soul.saveSettings({ provider: settings.provider, endpoint: settings.endpoint, model: settings.model, language: select.value, theme: settings.theme, companion: settings.companion });
        const state = await window.soul.snapshot();
        const p = state.assistant?.preferences || {}, c = state.assistant?.capabilities || {};
        await window.soul.configureAssistant({ autonomy: state.assistant?.autonomy, initiativeEnabled: state.assistant?.initiativeEnabled, reflectionEnabled: state.assistant?.reflectionEnabled, responseLength: p.responseLength, tone: p.tone, focusMode: p.focusMode, accessibility: p.accessibility, language: select.value, webResearch: c.webResearch, mediaPlayback: c.mediaPlayback, memoryLearning: c.memoryLearning });
      });
    } catch {}
  });
})();
