const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let state = null, settings = null, sending = false, backupCount = 0;
let mediaQueue = [], mediaIndex = -1;
const views = { chat: $('#chatView'), dashboard: $('#dashboardView'), apps: $('#appsView'), entertainment: $('#entertainmentView'), memory: $('#memoryView'), identity: $('#identityView'), settings: $('#settingsView') };
const t = (key, fallback) => window.eidovaraI18n?.t(key, fallback) || fallback || key;
const assistantPayload = (extra = {}) => {
  const p = state?.assistant?.preferences || {}, c = state?.assistant?.capabilities || {};
  return { autonomy: state?.assistant?.autonomy, initiativeEnabled: state?.assistant?.initiativeEnabled, reflectionEnabled: state?.assistant?.reflectionEnabled, responseLength: p.responseLength, tone: p.tone, focusMode: p.focusMode, accessibility: p.accessibility, language: $('#languageSelect')?.value || p.language || 'en', webResearch: c.webResearch, mediaPlayback: c.mediaPlayback, memoryLearning: c.memoryLearning, ...extra };
};

function activeConversation(){ return state?.conversations?.find(c=>c.id===state.activeConversationId) || state?.conversations?.[0]; }
function fmt(ts){ try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(ts));}catch{return '';} }
function setView(name){ if(!views[name])return;Object.values(views).forEach(v=>v.classList.remove('active')); views[name].classList.add('active'); $('#viewTitle').textContent = name==='chat' ? (activeConversation()?.title || 'Conversation') : ({dashboard:'Dashboard',apps:'Apps & Gaming',entertainment:'Entertainment',memory:'Memory',identity:'Identity & continuity',settings:'Settings'}[name]); if(innerWidth<861) $('#sidebar').classList.remove('open'); }
function el(tag, cls, text){ const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; }
function setupCategories(){return $$('input[name="setupCategory"]:checked').map(x=>x.value);}
function toggleStreamSetup(){$('#setupStreamFields').classList.toggle('hidden',!setupCategories().includes('stream-helper'));}
function openSetup(reconfigure=false){const setup=state.setup||{};$$('input[name="setupCategory"]').forEach(x=>{x.checked=(setup.categories||[]).includes(x.value);});$('#setupCustomNeeds').value=setup.customNeeds||'';if($('#setupAccessibility'))$('#setupAccessibility').value=state.assistant?.preferences?.accessibility||'';$('#setupObsUrl').value=setup.stream?.obsWebSocketUrl||'ws://127.0.0.1:4455';$('#setupStreamGoals').value=setup.stream?.goals||'';$('#cancelSetupBtn').classList.toggle('hidden',!reconfigure&&!setup.completed);$('#setupStatus').textContent='';toggleStreamSetup();$('#setupOverlay').classList.remove('hidden');}
async function openAdmin(){const status=await window.soul.adminStatus();$('#adminOverlay').classList.remove('hidden');$('#adminLoginStatus').textContent='';$('#adminPassword').value='';$('#adminLoginForm').classList.toggle('hidden',status.authorized);$('#adminPanelForm').classList.toggle('hidden',!status.authorized);$('#adminTitle').textContent=status.configured?'Private administration':'Create administrator password';$('#adminLoginHelp').textContent=status.configured?'Local access only. This session automatically locks after 15 minutes.':'Create a unique password of at least 12 characters for this installation. Eidovara cannot recover it.';$('#adminLoginButton').textContent=status.configured?'Unlock':'Create and unlock';$('#adminLoginForm').dataset.configured=String(Boolean(status.configured));if(status.authorized){$('#adminEdition').value=status.edition;$('#adminStoreUrl').value=status.storeUrl||'';$('#adminServiceUrl').value=status.serviceUrl||'';$('#adminPanelStatus').textContent=`Unlocked until ${new Date(status.expiresAt).toLocaleTimeString()}.`;}else $('#adminPassword').focus();}

function renderConversations(){ const list=$('#conversationList'); list.textContent=''; for(const c of state.conversations){ const row=el('button','conversation'+(c.id===state.activeConversationId?' active':'')); row.type='button'; const label=el('span','label',c.title||'Conversation'); const del=el('button','delete','×'); del.type='button'; del.title='Delete conversation'; del.addEventListener('click',async e=>{e.stopPropagation(); if(state.conversations.length<=1)return; state=await window.soul.deleteConversation(c.id); renderAll();}); row.append(label,del); row.addEventListener('click',async()=>{state=await window.soul.selectConversation(c.id); renderAll();setView('chat');}); list.append(row); } }
function externalLink(url,label){const a=el('button','web-link',label);a.type='button';a.addEventListener('click',()=>window.soul.openExternal(url));return a;}
function currentPlayer(){return mediaQueue[mediaIndex]?.type==='video'?$('#videoPlayer'):$('#audioPlayer');}
function mediaSignal(event,item=mediaQueue[mediaIndex]){if(!item||!['audio','video'].includes(item.type))return;window.soul.recordMedia({event,type:item.type,title:item.title,sourceUrl:item.sourceUrl}).catch(()=>{});}
function loadMedia(index,autoplay=true){if(!mediaQueue.length)return;const previous=mediaQueue[mediaIndex];if(previous&&index!==mediaIndex)mediaSignal('skip',previous);mediaIndex=(index+mediaQueue.length)%mediaQueue.length;const item=mediaQueue[mediaIndex],audio=$('#audioPlayer'),video=$('#videoPlayer'),player=item.type==='video'?video:audio;audio.pause();video.pause();audio.classList.toggle('hidden',item.type==='video');video.classList.toggle('hidden',item.type!=='video');player.src=item.url;$('#mediaTitle').textContent=item.title||'Untitled media';$('#mediaKind').textContent=`${item.local?'local ':''}${item.type} · ${mediaIndex+1} of ${mediaQueue.length}`;$('#mediaFavoriteBtn').textContent='♡';$('#mediaSourceBtn').disabled=!item.sourceUrl;$('#mediaDock').classList.remove('hidden');mediaSignal('play',item);if(autoplay)player.play().catch(()=>{});}
function playMedia(items,index,opts={}){const mode=state?.assistant?.capabilities?.mediaPlayback||'confirm';if(mode==='disabled'){alert(t('mediaDisabled','Media playback is disabled in Soul behavior settings.'));return;}const selected=items[index];if(mode==='confirm'&&!opts.alreadyConfirmed){if(!window.confirm(`${t('mediaConfirm','Play this media in Eidovara:')} ${selected?.title||''}`.trim()))return;}mediaQueue=items.filter(m=>m.type==='audio'||m.type==='video');loadMedia(Math.max(0,mediaQueue.indexOf(selected)));}
function renderResearch(target,research){if(!research)return;const panel=el('div','research-panel');panel.append(el('div','research-title',`Internet results · ${fmt(research.fetchedAt)}`));for(const s of research.sources||[]){const row=el('div','research-source');row.append(externalLink(s.url,s.title),el('small','',s.description||''));panel.append(row);}if(research.media?.length){const grid=el('div','media-grid');research.media.forEach((m,index)=>{const card=el('div','media-card');if(m.type==='image'){const img=document.createElement('img');img.src=m.url;img.alt=m.title;img.loading='lazy';card.append(img);}else{const play=el('button','media-launch',m.type==='audio'?'▶ Play audio':'▶ Play video');play.type='button';play.addEventListener('click',()=>playMedia(research.media,index));card.append(play);}card.append(externalLink(m.sourceUrl,m.title));grid.append(card);});panel.append(grid);}target.append(panel);}
function renderMessages(){ const box=$('#messages'); box.textContent=''; const c=activeConversation(); const messages=c?.messages||[]; $('#welcome').classList.toggle('hidden',messages.length>0); for(const m of messages){ const wrap=el('div',`message ${m.role==='assistant'?'assistant':'user'}`); if(m.role==='assistant'){ const av=el('div','soul-mark avatar'); av.append(el('span')); wrap.append(av); } const content=el('div'); const bubble=el('div','bubble',m.content); const meta=el('div','message-meta',fmt(m.at)); content.append(bubble);renderResearch(content,m.webResearch);content.append(meta);wrap.append(content); box.append(wrap); } requestAnimationFrame(()=>{$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight;}); }
function renderMemory(){ const box=$('#memoryCards'); box.textContent=''; const mem=[...(state.memories||[])].reverse(); if(!mem.length){box.append(el('div','empty',t('emptyMemory','No durable memories yet.')));return;} for(const m of mem){ const card=el('div','card memory-card'); const body=el('div'); const p=el('div','',m.content); const sm=el('small','',`${m.active?'active':'inactive'} · ${m.kind} · confidence ${Math.round((m.confidence||0)*100)}%`); body.append(p,sm); const b=el('button','forget',m.active?'Forget':'Inactive'); b.type='button'; b.disabled=!m.active; b.addEventListener('click',async()=>{await window.soul.forget(m.id);state=await window.soul.snapshot();renderAll();}); card.append(body,b); box.append(card); } }
function renderIdentity(){ const sm=state.continuity.selfModel; const self=$('#selfModel'); self.textContent=''; for(const [k,v] of [['Name',sm.name],['Architecture',sm.architecture],['Protected identity',String(sm.protectedIdentity)],['Core values',sm.coreValues.join(', ')]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));self.append(r);} const traits=$('#traits');traits.textContent='';for(const [k,v] of Object.entries(state.personality).filter(([,v])=>typeof v==='number')){const r=el('div','trait');r.append(el('span','',k),(()=>{const b=el('div','bar');const f=el('div','fill');f.style.width=`${Math.round(v*100)}%`;b.append(f);return b;})(),el('span','',`${Math.round(v*100)}%`));traits.append(r);} const rel=$('#relationship');rel.textContent='';for(const [k,v] of [['Style',state.relationship.style],['Temporary initiative',String(state.relationship.temporaryInitiative)],['Trust',`${Math.round(state.relationship.trust*100)}%`],['Comfort',`${Math.round(state.relationship.comfort*100)}%`]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));rel.append(r);} const p=$('#policy');p.textContent='';for(const [k,v] of [['Mode',state.policy.mode],['Adult status confirmed',String(state.policy.adultStatusConfirmed)],['Adult Soul enabled',String(state.policy.adultSoulEnabled)],['Current consent',String(state.policy.currentConsent)],['Consent scope',state.policy.consentScope||'none'],['Active boundaries',String((state.policy.boundaries||[]).filter(b=>b.active).length)]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));p.append(r);} }
function applyEditionGates(){ const premium=settings?.edition==='premium'; const rgb=$('#themeRgb'); if(rgb){rgb.disabled=!premium; if(!premium) rgb.checked=false;} const search=$('#searchApiKeyInput'), clearSearch=$('#clearSearchKeyInput'); if(search) search.disabled=!premium; if(clearSearch) clearSearch.disabled=!premium; const compatible=$('#providerSelect option[value="compatible"]'); if(compatible) compatible.disabled=!premium; if(!premium&&$('#providerSelect')?.value==='compatible') $('#providerSelect').value='offline'; const note=$('#premiumFieldsNote'); if(note) note.textContent=premium?t('premiumUnlocked','Premium test gates are on: remote endpoints, Brave search key, RGB, and unlimited apps.'):t('premiumLocked','Free: offline/local models, Wikipedia/Wikimedia research, up to 3 apps. RGB, Brave key, and remote endpoints stay Premium.'); }
function renderStatus(){ const premium=settings?.edition==='premium'; $('#modePill').textContent=`${state.policy.mode==='adult'?'Adult Soul':'Standard Soul'} · ${premium?'Premium':'Free'}`; const labels={offline:'Soul Offline',local:'Local model',compatible:'Connected model'}; $('#providerLabel').textContent=labels[settings?.provider]||'Offline'; $('#editionTitle').textContent=premium?'Eidovara Premium':'Eidovara Free'; $('#editionDescription').textContent=premium?'The locally implemented Premium feature gates are enabled for testing on this installation.':'Core workspace features with offline/local models, memory, media, backups, updates, and up to three linked apps.'; $('#upgradeBtn').classList.toggle('hidden',premium||!settings?.storeUrl); applyEditionGates(); }
function applyTheme(){const t=settings?.theme||{};const root=document.documentElement;root.style.setProperty('--bg',t.background||'#080c16');root.style.setProperty('--panel',t.panel||'#101828');root.style.setProperty('--accent',t.accent||'#8f7cff');root.style.setProperty('--surface-opacity',`${Math.max(65,Math.min(100,Number(t.transparency)||96))}%`);document.body.classList.toggle('rgb-effects',Boolean(t.rgbEffects)&&!t.gamingMode);document.body.classList.toggle('gaming-mode',Boolean(t.gamingMode));}
function populateVoices(){if(!('speechSynthesis' in window))return;const current=$('#voiceSelect').value||(settings?.companion?.voiceName||'');const voices=speechSynthesis.getVoices();$('#voiceSelect').textContent='';const fallback=el('option','','Windows default');fallback.value='';$('#voiceSelect').append(fallback);for(const voice of voices){const option=el('option','',`${voice.name} (${voice.lang})`);option.value=voice.name;$('#voiceSelect').append(option);}$('#voiceSelect').value=[...$('#voiceSelect').options].some(x=>x.value===current)?current:'';}
function applyCompanion(){const c=settings?.companion||{};const gates=state?.policy?.adultStatusConfirmed===true&&state?.policy?.adultSoulEnabled===true&&state?.policy?.currentConsent===true&&state?.policy?.mode==='adult';const avatar=$('#companionAvatar'),mode=c.avatarMode||'3d';avatar.className=`companion-avatar mode-${mode} motion-${c.motion||'gentle'}${gates&&c.adultPresentation?' adult-presentation':''}`;const height=Math.max(0,Math.min(100,Number(c.bodyHeight)||50)),build=Math.max(0,Math.min(100,Number(c.bodyBuild)||50)),curves=Math.max(0,Math.min(100,Number(c.bodyCurves)||50));avatar.style.transform=mode==='2d'?`scaleX(${.82+build*.0036}) scaleY(${.82+height*.0036})`:'';avatar.style.borderRadius=mode==='2d'?`${38+curves*.12}% ${38+curves*.12}% 46% 46%`:'';$('#avatarMode').value=mode;$('#avatarMotion').value=c.motion||'gentle';$('#voiceEnabled').checked=Boolean(c.voiceEnabled);$('#voiceRate').value=c.rate||1;$('#voicePitch').value=c.pitch||1;$('#adultAvatarSettings').classList.toggle('hidden',!gates);$('#adultPresentation').checked=gates&&Boolean(c.adultPresentation);$('#bodyHeight').value=c.bodyHeight??50;$('#bodyBuild').value=c.bodyBuild??50;$('#bodyCurves').value=c.bodyCurves??50;populateVoices();}
function speakSoul(text,force=false){if(!('speechSynthesis' in window)||(!force&&!settings?.companion?.voiceEnabled))return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(String(text||'').slice(0,8000));const c=settings?.companion||{};utterance.rate=Number(c.rate)||1;utterance.pitch=Number(c.pitch)||1;utterance.voice=speechSynthesis.getVoices().find(v=>v.name===c.voiceName)||null;utterance.onstart=()=>$('#companionAvatar').classList.add('speaking');utterance.onend=utterance.onerror=()=>$('#companionAvatar').classList.remove('speaking');speechSynthesis.speak(utterance);}
function rendererCapabilities(){
  const video=document.createElement('video'),audio=document.createElement('audio');
  const supported=(element,type)=>Boolean(element.canPlayType(type));
  return {
    display:{highDynamicRange:Boolean(window.matchMedia?.('(dynamic-range: high)').matches),colorGamutP3:Boolean(window.matchMedia?.('(color-gamut: p3)').matches)},
    video:{h264:supported(video,'video/mp4; codecs="avc1.42E01E"'),hevc:supported(video,'video/mp4; codecs="hvc1"'),vp9:supported(video,'video/webm; codecs="vp9"'),av1:supported(video,'video/mp4; codecs="av01.0.05M.08"'),pictureInPicture:'pictureInPictureEnabled' in document,fullscreen:document.fullscreenEnabled},
    audio:{aac:supported(audio,'audio/mp4; codecs="mp4a.40.2"'),mp3:supported(audio,'audio/mpeg'),opus:supported(audio,'audio/webm; codecs="opus"'),flac:supported(audio,'audio/flac'),webAudio:Boolean(window.AudioContext||window.webkitAudioContext)},
    input:{gamepadApi:'getGamepads' in navigator,connectedGamepads:'getGamepads' in navigator?[...navigator.getGamepads()].filter(Boolean).length:0},
    browser:{mediaSession:'mediaSession' in navigator,logicalProcessors:navigator.hardwareConcurrency||null,deviceMemoryGiB:navigator.deviceMemory||null}
  };
}
function renderApps(){
  const grid=$('#appsGrid');grid.textContent='';const apps=settings?.apps||[];
  if(!apps.length){
    const empty=el('div','empty-state');
    empty.append(el('strong','',t('emptyAppsTitle','No applications linked yet')), el('p','',t('emptyAppsBody','Build a Windows shelf of titles you already trust and are permitted to use.')));
    const list=el('ol');
    for (const key of ['emptyAppsStep1','emptyAppsStep2','emptyAppsStep3']) list.append(el('li','',t(key)));
    const actions=el('div','empty-actions');
    const discover=el('button','',t('discoverApps','Discover installed apps')); discover.type='button'; discover.addEventListener('click',()=>$('#discoverAppsBtn').click());
    const choose=el('button','secondary',t('chooseFile','＋ Choose file')); choose.type='button'; choose.addEventListener('click',()=>$('#addAppBtn').click());
    actions.append(discover,choose); empty.append(list,actions); grid.append(empty); return;
  }
  for(const app of apps){const card=el('div','app-card');const info=el('div','app-info');info.append(el('strong','',app.name),el('small','',app.path));const actions=el('div','app-actions');const launch=el('button','', t('launchApp','Launch'));launch.type='button';launch.addEventListener('click',async()=>{try{$('#appsStatus').textContent=`Asking Windows to open ${app.name}…`;const result=await window.soul.launchApplication(app.id);if(result?.cancelled){$('#appsStatus').textContent=t('launchCancelled','Launch cancelled.');return;}$('#appsStatus').textContent=`Launched ${app.name}. Windows opened the selected shortcut or executable; Eidovara did not inject into that process.`;}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});const remove=el('button','secondary','Remove');remove.type='button';remove.addEventListener('click',async()=>{settings=await window.soul.removeApplication(app.id);applyTheme();renderApps();renderDashboard();});actions.append(launch,remove);card.append(info,actions);grid.append(card);}
}
async function refreshBackups(){const select=$('#backupSelect');select.textContent='';const backups=await window.soul.listBackups();backupCount=backups.length;for(const b of backups){const o=el('option','',`${new Date(b.createdAt).toLocaleString()} · ${Math.ceil(b.bytes/1024)} KB`);o.value=b.name;select.append(o);}if(!backups.length)select.append(el('option','',t('noBackups','No backups yet. Create one before changing providers or resetting.')));$('#restoreBackupBtn').disabled=!backups.length;if(!backups.length && !$('#backupStatus').textContent) $('#backupStatus').textContent=t('noBackups','No backups yet. Create one before changing providers or resetting.');}
function renderDashboard(){
  const box=$('#dashboardGrid');box.textContent='';
  const roles=(state.setup?.categories||[]);
  const memories=(state.memories||[]).filter(x=>x.active).length;
  const apps=(settings?.apps||[]).length;
  const taste=Object.keys(state.entertainment?.taste||{}).length;
  const items=[
    {label:t('dashFocus','Focus'), value:state.assistant?.preferences?.focusMode||'general', next:t('focusSession','Focus session'), run:()=>{setView('chat');send('Plan a focused session for my current priority.');}},
    {label:t('dashRoles','Roles'), value:roles.length?roles.join(', '):t('notConfigured','not configured'), next:t('nextConfigure','Configure roles'), run:()=>openSetup(true)},
    {label:t('dashMemory','Memory'), value:`${memories} active`, next:t('nextMemory','Review memory'), run:()=>setView('memory')},
    {label:t('dashApps','Apps'), value:`${apps} linked`, next:t('nextAddApps','Add a trusted app'), run:()=>setView('apps')},
    {label:t('dashMedia','Entertainment'), value:taste?`${taste} taste signals`:'none yet', next:t('nextEntertainment','Open Entertainment'), run:()=>setView('entertainment')},
    {label:t('dashPrivacy','Workspace'), value:settings?.provider==='offline'?t('offlineFirst','offline-first'):t('connectedProvider','connected provider'), next:t('nextSettings','Open settings'), run:()=>setView('settings')},
    {label:t('dashBackups','Backups'), value:String(backupCount), next:t('nextBackup','Create a backup'), run:()=>{setView('settings');$('#backupSection')?.scrollIntoView({behavior:'smooth',block:'center'});}},
    {label:t('dashHealth','Diagnostics'), value:settings?.encryptionAvailable?'OS-protected':'local files', next:t('nextDiagnostics','Show diagnostics'), run:()=>{setView('settings');$('#diagnosticsBtn').click();}}
  ];
  for(const item of items){const c=el('button','dashboard-card');c.type='button';c.append(el('small','',item.label),el('strong','',item.value),el('span','next',item.next));c.addEventListener('click',item.run);box.append(c);}
}
function renderEntertainment(){
  const favorites=$('#entertainmentFavorites'),recent=$('#entertainmentRecent'),mix=$('#entertainmentMix');
  favorites.textContent='';recent.textContent='';if(mix)mix.textContent='';
  const e=state.entertainment||{};
  for(const item of [...(e.favorites||[])].slice(-8).reverse()){const row=el('div','kv');row.append(el('span','',item.type),el('span','',item.title));favorites.append(row);}
  for(const item of [...(e.history||[])].slice(-10).reverse()){const row=el('div','kv');row.append(el('span','',item.event),el('span','',item.title));recent.append(row);}
  if(!favorites.children.length)favorites.append(el('div','empty',t('emptyFavorites','Favorite media will appear here after you heart something in the player.')));
  if(!recent.children.length)recent.append(el('div','empty',t('emptyRecent','Play, skip, and complete events will appear here. Local file paths are not stored in taste records.')));
  const seeds=Object.entries(e.taste||{}).sort((a,b)=>b[1]-a[1]).filter(([,score])=>score>0).slice(0,4).map(([title])=>title);
  if(mix) mix.textContent=seeds.length?`${seeds.join(', ')}. Spotify and YouTube remain official HTTPS searches in your browser.` : t('mixEmpty','Play or favorite something to grow a local mix. Suggestions stay on this device.');
}
function renderAll(){ renderConversations();renderMessages();renderDashboard();renderApps();renderEntertainment();renderMemory();renderIdentity();renderStatus();applyTheme();applyCompanion();if($('#assistantAutonomy')){const p=state.assistant?.preferences||{},c=state.assistant?.capabilities||{};$('#assistantAutonomy').value=state.assistant?.autonomy||'balanced';$('#responseLength').value=p.responseLength||'balanced';$('#responseTone').value=p.tone||'natural';$('#focusMode').value=p.focusMode||'general';$('#assistantAccessibility').value=p.accessibility||'';$('#webResearchPolicy').value=c.webResearch||'ask';$('#mediaPlaybackPolicy').value=c.mediaPlayback||'confirm';$('#memoryLearning').checked=c.memoryLearning!=='disabled';$('#assistantInitiative').checked=state.assistant?.initiativeEnabled!==false;$('#assistantReflection').checked=state.assistant?.reflectionEnabled!==false;}$('#viewTitle').textContent=activeConversation()?.title||'Conversation'; }
function addTyping(){ const wrap=el('div','message assistant');const av=el('div','soul-mark avatar');av.append(el('span'));const b=el('div','bubble typing','Soul is thinking…');wrap.append(av,b);wrap.id='typing';$('#messages').append(wrap);$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight; }
function autoSize(){ const ta=$('#messageInput');ta.style.height='auto';ta.style.height=Math.min(180,ta.scrollHeight)+'px'; }
async function send(text){ text=String(text||'').trim();if(!text||sending)return;sending=true;$('#sendBtn').disabled=true;$('#messageInput').value='';autoSize(); if(!activeConversation()?.messages?.length) $('#welcome').classList.add('hidden'); const user=el('div','message user');const c=el('div');c.append(el('div','bubble',text));user.append(c);$('#messages').append(user);addTyping();try{const res=await window.soul.send(text);state=res.state;renderAll();const replies=(activeConversation()?.messages||[]).filter(x=>x.role==='assistant');speakSoul(replies.at(-1)?.content);if(res.providerError){const note=el('div','error-note',`Model connection issue: ${res.providerError}`);$('#messages').append(note);}if(res.internetError){const note=el('div','error-note',`Internet search issue: ${res.internetError}`);$('#messages').append(note);}}catch(err){$('#typing')?.remove();const note=el('div','error-note',String(err?.message||err));$('#messages').append(note);}finally{sending=false;$('#sendBtn').disabled=false;$('#messageInput').focus();} }

$('#chatForm').addEventListener('submit',e=>{e.preventDefault();send($('#messageInput').value);});
$('#messageInput').addEventListener('input',autoSize);$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.currentTarget.value);}});
$$('[data-starter]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.starter)));
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#newChatBtn').addEventListener('click',async()=>{state=await window.soul.newConversation();renderAll();setView('chat');$('#messageInput').focus();});
$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const v=$('#memoryInput').value.trim();if(!v)return;await window.soul.remember(v,{kind:'preference'});$('#memoryInput').value='';state=await window.soul.snapshot();renderAll();});
$$('[data-command]').forEach(b=>b.addEventListener('click',async()=>{const command=b.dataset.command;if((command==='adult status confirmed'||command==='enable adult soul')&&!state.policy?.adultStatusConfirmed){const accepted=window.confirm(window.eidovaraI18n.t('adultWarning'));if(!accepted)return;if(command==='enable adult soul')await send('adult status confirmed');}setView('chat');await send(command);}));
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();$('#settingsStatus').textContent='Saving…';try{const provider=$('#providerSelect').value, endpoint=$('#endpointInput').value.trim(), model=$('#modelInput').value.trim();settings=await window.soul.saveSettings({provider,endpoint,model,language:$('#languageSelect').value,apiKey:$('#apiKeyInput').value,clearApiKey:$('#clearKeyInput').checked,searchApiKey:$('#searchApiKeyInput').value,clearSearchApiKey:$('#clearSearchKeyInput').checked,theme:{background:$('#themeBackground').value,panel:$('#themePanel').value,accent:$('#themeAccent').value,transparency:Number($('#themeTransparency').value),rgbEffects:$('#themeRgb').checked,gamingMode:$('#gamingModeInput').checked},companion:{avatarMode:$('#avatarMode').value,motion:$('#avatarMotion').value,voiceEnabled:$('#voiceEnabled').checked,voiceName:$('#voiceSelect').value,rate:Number($('#voiceRate').value),pitch:Number($('#voicePitch').value),adultPresentation:$('#adultPresentation').checked,bodyHeight:Number($('#bodyHeight').value),bodyBuild:Number($('#bodyBuild').value),bodyCurves:Number($('#bodyCurves').value)}});$('#apiKeyInput').value='';$('#searchApiKeyInput').value='';$('#clearKeyInput').checked=false;$('#clearSearchKeyInput').checked=false;const labels={offline:'Soul Offline',local:'Local model',compatible:'Connected model'};let note=`Settings saved. Provider: ${labels[settings.provider]||settings.provider}. Language: ${settings.language||'en'}.`;if(settings.provider!=='offline'&&(!endpoint||!model)) note+=' Add an endpoint and model before leaving offline fallback.';$('#settingsStatus').textContent=note;applyTheme();applyCompanion();renderStatus();renderDashboard();}catch(err){$('#settingsStatus').textContent=String(err?.message||err);}});
$('#addAppBtn').addEventListener('click',async()=>{try{settings=await window.soul.addApplication();applyTheme();renderApps();$('#appsStatus').textContent='Application list updated.';}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});
const localMediaButton=el('button','secondary',t('openLocalMedia','Open local media'));localMediaButton.type='button';localMediaButton.id='openLocalMediaBtn';localMediaButton.addEventListener('click',async()=>{try{const item=await window.soul.selectLocalMedia();if(item)playMedia([item],0,{alreadyConfirmed:true});}catch(err){alert(String(err?.message||err));}});$('#entertainmentView .panel-head').append(localMediaButton);
$('#discoverAppsBtn').addEventListener('click',async()=>{
  const grid=$('#discoveredAppsGrid');
  try {
    $('#appsStatus').textContent='Scanning Windows Start Menu shortcuts…';
    const apps=await window.soul.discoverApplications();
    grid.textContent='';
    for(const app of apps){
      const card=el('div','app-card'); card.append(el('strong','',app.name));
      const add=el('button','secondary','Add'); add.type='button';
      add.addEventListener('click',async()=>{try{settings=await window.soul.addDiscoveredApplication(app.id);renderApps();add.disabled=true;add.textContent='Added';}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});
      card.append(add); grid.append(card);
    }
    if(!apps.length) grid.append(el('div','empty','No Start Menu shortcuts were found. You can still choose a trusted .exe or .lnk file. Discovery reads shortcut names locally and does not open them.'));
    $('#discoveredAppsCard').classList.remove('hidden');
    $('#appsStatus').textContent=`Found ${apps.length} local application shortcuts.`;
  } catch(err) { $('#appsStatus').textContent=String(err?.message||err); }
});
$('#gamingModeInput').addEventListener('change',async()=>{try{settings=await window.soul.saveSettings({provider:settings.provider,endpoint:settings.endpoint,model:settings.model,theme:{...(settings.theme||{}),gamingMode:$('#gamingModeInput').checked}});if($('#gamingModeInput').checked&&'speechSynthesis' in window)speechSynthesis.cancel();applyTheme();$('#appsStatus').textContent=$('#gamingModeInput').checked?'Low-overhead mode enabled for Eidovara.':'Low-overhead mode disabled.';}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});
$('#themeTransparency').addEventListener('input',()=>{$('#themeTransparencyValue').textContent=`${$('#themeTransparency').value}%`;});
$('#companionAvatar').addEventListener('click',()=>{$('#avatarMode').value='hidden';$('#settingsStatus').textContent='Avatar hidden. Save Settings to keep this choice.';$('#companionAvatar').classList.add('mode-hidden');});
$('#voicePreviewBtn').addEventListener('click',()=>{settings.companion={...(settings.companion||{}),voiceName:$('#voiceSelect').value,rate:Number($('#voiceRate').value),pitch:Number($('#voicePitch').value)};speakSoul('Hello. I am Soul, your Eidovara companion.',true);});
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(Recognition){$('#voiceInputBtn').classList.remove('hidden');const recognition=new Recognition();recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{$('#voiceSupportStatus').textContent='Listening… microphone audio is used only for this dictation session.';};recognition.onresult=e=>{$('#messageInput').value=[...e.results].map(r=>r[0].transcript).join(' ');autoSize();};recognition.onerror=e=>{$('#voiceSupportStatus').textContent=`Voice input unavailable: ${e.error}. You can continue typing.`;};recognition.onend=()=>{if(!$('#voiceSupportStatus').textContent.startsWith('Voice input unavailable'))$('#voiceSupportStatus').textContent='Dictation complete. Review the text before sending.';};$('#voiceInputBtn').addEventListener('click',()=>recognition.start());}else{$('#voiceSupportStatus').textContent='Installed Windows voices are available for playback. Voice input is not supported by this system build.';}
if('speechSynthesis' in window)speechSynthesis.onvoiceschanged=populateVoices;
$('#openDataBtn').addEventListener('click',()=>window.soul.openDataFolder());
$('#privacyNoticeBtn').addEventListener('click',()=>window.soul.openExternal('https://projectsoulbytmb.github.io/project---soul/privacy.html'));
$('#securityCenterBtn').addEventListener('click',()=>window.soul.openExternal('https://projectsoulbytmb.github.io/project---soul/security.html'));
$('#licensingBtn').addEventListener('click',()=>window.soul.openExternal('https://projectsoulbytmb.github.io/project---soul/licensing.html'));
$('#upgradeBtn').addEventListener('click',()=>{if(settings?.storeUrl)window.soul.openExternal(settings.storeUrl).catch(err=>{$('#settingsStatus').textContent=String(err?.message||err);});});
$('#assistantBehaviorForm').addEventListener('submit',async e=>{e.preventDefault();try{state=await window.soul.configureAssistant({autonomy:$('#assistantAutonomy').value,initiativeEnabled:$('#assistantInitiative').checked,reflectionEnabled:$('#assistantReflection').checked,responseLength:$('#responseLength').value,tone:$('#responseTone').value,focusMode:$('#focusMode').value,accessibility:$('#assistantAccessibility').value,language:$('#languageSelect').value,webResearch:$('#webResearchPolicy').value,mediaPlayback:$('#mediaPlaybackPolicy').value,memoryLearning:$('#memoryLearning').checked?'enabled':'disabled'});$('#assistantBehaviorStatus').textContent=t('behaviorSaved','Behavior settings saved. Language, tone, and accessibility remain as set.');renderAll();}catch(err){$('#assistantBehaviorStatus').textContent=String(err?.message||err);}});
$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{setView('chat');send(b.dataset.quick);}));
$('#diagnosticsBtn').addEventListener('click',async()=>{
  const d=await window.soul.diagnostics();
  d.rendererCapabilities=rendererCapabilities();
  const codecs=d.rendererCapabilities||{};
  const summary=$('#diagnosticsSummary');
  if(summary){
    summary.textContent='';
    const rows=[
      ['Eidovara', `${d.version} · ${d.platform}/${d.arch}`],
      ['Chromium', `${d.chromium || 'n/a'} · GPU accel ${d.hardwareAcceleration?'on':'off'}`],
      ['Codecs', `H.264 ${codecs.video?.h264?'yes':'no'} · VP9 ${codecs.video?.vp9?'yes':'no'} · AV1 ${codecs.video?.av1?'yes':'no'} · AAC ${codecs.audio?.aac?'yes':'no'}`],
      ['Protection', d.settings?.encryptionAvailable ? 'OS credential protection available' : 'OS credential protection unavailable'],
      ['Safety log', `${d.localSafetyReportCount||0} local reports (not sent automatically)`]
    ];
    for(const [k,v] of rows){const line=el('div','kv');line.append(el('span','',k),el('span','',v));summary.append(line);}
  }
  $('#diagnosticsText').textContent=JSON.stringify(d,null,2);
  $('#diagnosticsCard').classList.remove('hidden');
});
async function checkUpdates(silent=false){try{const u=await window.soul.checkForUpdates();if(!u.configured){if(!silent)$('#updateStatus').textContent='This development build has no published release channel.';return;}if(u.available){$('#updateStatus').textContent=`Version ${u.version} is available.${u.notes?' '+u.notes:''}`;$('#installUpdateBtn').classList.remove('hidden');}else if(!silent){ $('#updateStatus').textContent=`Eidovara ${u.currentVersion} is current.`;}}catch(err){if(!silent)$('#updateStatus').textContent=String(err?.message||err);}}
$('#checkUpdateBtn').addEventListener('click',()=>checkUpdates(false));$('#installUpdateBtn').addEventListener('click',async()=>{try{$('#updateStatus').textContent='Downloading and verifying update…';const result=await window.soul.installUpdate();$('#updateStatus').textContent=result.cancelled?'Update cancelled.':'Verified installer launched.';}catch(err){$('#updateStatus').textContent=String(err?.message||err);}});
$$('input[name="setupCategory"]').forEach(x=>x.addEventListener('change',toggleStreamSetup));$('#openSetupBtn').addEventListener('click',()=>openSetup(true));$('#cancelSetupBtn').addEventListener('click',()=>$('#setupOverlay').classList.add('hidden'));$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();const categories=setupCategories();const access=$('#setupAccessibility')?.value.trim()||'';if(!categories.length&&!$('#setupCustomNeeds').value.trim()&&!access){$('#setupStatus').textContent='Choose at least one role or describe what you need.';return;}try{$('#setupStatus').textContent='Saving…';state=await window.soul.configureSetup({categories,customNeeds:$('#setupCustomNeeds').value,obsWebSocketUrl:$('#setupObsUrl').value,streamGoals:$('#setupStreamGoals').value});if(access||categories.includes('accessibility')) state=await window.soul.configureAssistant(assistantPayload({accessibility:access || state.assistant?.preferences?.accessibility || ''}));$('#setupOverlay').classList.add('hidden');renderAll();}catch(err){$('#setupStatus').textContent=String(err?.message||err);}});
$('#mediaPrevBtn').addEventListener('click',()=>loadMedia(mediaIndex-1));$('#mediaNextBtn').addEventListener('click',()=>loadMedia(mediaIndex+1));$('#mediaPlayBtn').addEventListener('click',()=>{const p=currentPlayer();if(!p)return;p.paused?p.play().catch(()=>{}):p.pause();});$('#mediaFavoriteBtn').addEventListener('click',async()=>{const item=mediaQueue[mediaIndex];if(!item)return;await window.soul.recordMedia({event:'favorite',type:item.type,title:item.title,sourceUrl:item.sourceUrl});$('#mediaFavoriteBtn').textContent='♥';});$('#mediaSimilarBtn').addEventListener('click',async()=>{const item=mediaQueue[mediaIndex];if(!item)return;const taste=await window.soul.entertainment();const favorites=taste.topTitles.slice(0,3).map(x=>x.title).join(', ');send(`Find something similar to my favorite music: ${item.title}${favorites?`, considering ${favorites}`:''}`);});$('#mediaSpotifyBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(`https://open.spotify.com/search/${encodeURIComponent(item.title)}`);});$('#mediaYouTubeBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(`https://www.youtube.com/results?search_query=${encodeURIComponent(item.title)}`);});$('#mediaSourceBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(item.sourceUrl);});$('#mediaCloseBtn').addEventListener('click',()=>{const p=currentPlayer();p?.pause();$('#mediaDock').classList.add('hidden');});function completeMedia(){const next=mediaIndex+1;mediaSignal('complete');mediaIndex=-1;loadMedia(next);}$('#audioPlayer').addEventListener('ended',completeMedia);$('#videoPlayer').addEventListener('ended',completeMedia);
$('#backupBtn').addEventListener('click',async()=>{try{$('#backupStatus').textContent='Creating local snapshot…';const b=await window.soul.createBackup();$('#backupStatus').textContent=`Created ${b.name} (${Math.ceil(b.bytes/1024)} KB). Restore is available from the list below.`;await refreshBackups();renderDashboard();}catch(err){$('#backupStatus').textContent=String(err?.message||err);}});
$('#refreshBackupsBtn').addEventListener('click',()=>refreshBackups().then(()=>{$('#backupStatus').textContent=backupCount?`${backupCount} local snapshot${backupCount===1?'':'s'} available.` : t('noBackups');renderDashboard();}).catch(err=>{$('#backupStatus').textContent=String(err?.message||err);}));
$('#restoreBackupBtn').addEventListener('click',async()=>{const name=$('#backupSelect').value;if(!name||name.startsWith('No backups')||!confirm('Restore this backup and replace the current profile state?'))return;try{state=await window.soul.restoreBackup(name);renderAll();$('#backupStatus').textContent=`Restored ${name}. Conversations, memories, and Soul continuity now match that snapshot.`;await refreshBackups();renderDashboard();}catch(err){$('#backupStatus').textContent=String(err?.message||err);}});
$('#resetBtn').addEventListener('click',async()=>{if(!confirm('Reset the current Soul profile and local conversation history?'))return;state=await window.soul.reset();renderAll();setView('chat');});
document.addEventListener('keydown',e=>{if(e.ctrlKey&&!e.shiftKey&&!e.altKey&&e.key.toLowerCase()==='a'){e.preventDefault();openAdmin().catch(err=>alert(String(err?.message||err)));}});
$('#adminCancelBtn').addEventListener('click',()=>$('#adminOverlay').classList.add('hidden'));
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();try{const password=$('#adminPassword').value;const status=$('#adminLoginForm').dataset.configured==='true'?await window.soul.adminLogin(password):await window.soul.adminConfigure(password);$('#adminPassword').value='';$('#adminLoginForm').classList.add('hidden');$('#adminPanelForm').classList.remove('hidden');$('#adminEdition').value=status.edition;$('#adminStoreUrl').value=status.storeUrl||'';$('#adminServiceUrl').value=status.serviceUrl||'';$('#adminPanelStatus').textContent=`Unlocked until ${new Date(status.expiresAt).toLocaleTimeString()}.`;}catch(err){$('#adminLoginStatus').textContent=String(err?.message||err);}});
$('#adminPanelForm').addEventListener('submit',async e=>{e.preventDefault();try{const status=await window.soul.adminSave({edition:$('#adminEdition').value,storeUrl:$('#adminStoreUrl').value.trim(),serviceUrl:$('#adminServiceUrl').value.trim()});settings=await window.soul.getSettings();renderAll();$('#adminPanelStatus').textContent=`Saved ${status.edition} edition, store, and HTTPS service configuration.`;}catch(err){$('#adminPanelStatus').textContent=String(err?.message||err);}});
$('#adminLockBtn').addEventListener('click',async()=>{await window.soul.adminLogout();$('#adminOverlay').classList.add('hidden');});
$('#adminStoreBtn').addEventListener('click',()=>{const url=$('#adminStoreUrl').value.trim();if(!url){$('#adminPanelStatus').textContent='Configure an HTTPS store link first.';return;}window.soul.openExternal(url).catch(err=>{$('#adminPanelStatus').textContent=String(err?.message||err);});});
$('#adminServiceBtn').addEventListener('click',async()=>{try{await window.soul.adminSave({edition:$('#adminEdition').value,storeUrl:$('#adminStoreUrl').value.trim(),serviceUrl:$('#adminServiceUrl').value.trim()});const result=await window.soul.checkService();$('#adminPanelStatus').textContent=result.configured?(result.online?`${result.service} ${result.version} is online.`:'Service responded but is unhealthy.'):'Configure an HTTPS service URL first.';}catch(err){$('#adminPanelStatus').textContent=String(err?.message||err);}});
$('#ageGateAcceptBtn').addEventListener('click',async()=>{settings=await window.soul.acceptAgeGate();$('#ageGateOverlay').classList.add('hidden');if(!state.setup?.completed)openSetup(false);});
$('#ageGateDeclineBtn').addEventListener('click',()=>window.soul.declineAgeGate());

(async function init(){ try{[state,settings]=await Promise.all([window.soul.snapshot(),window.soul.getSettings()]);$('#providerSelect').value=settings.provider;$('#endpointInput').value=settings.endpoint||'';$('#modelInput').value=settings.model||'';$('#apiKeyInput').placeholder=settings.hasApiKey?'Stored securely — leave blank to keep':'API key';$('#searchApiKeyInput').placeholder=settings.hasSearchApiKey?'Stored securely — leave blank to keep':'Brave Search API key';const theme=settings.theme||{};$('#themeBackground').value=theme.background||'#080c16';$('#themePanel').value=theme.panel||'#101828';$('#themeAccent').value=theme.accent||'#8f7cff';$('#themeTransparency').value=theme.transparency||96;$('#themeTransparencyValue').textContent=`${theme.transparency||96}%`;$('#themeRgb').checked=Boolean(theme.rgbEffects);$('#gamingModeInput').checked=Boolean(theme.gamingMode);await refreshBackups().catch(()=>{});renderAll();setView('chat');window.addEventListener('eidovara:locale',()=>{const mediaBtn=$('#openLocalMediaBtn');if(mediaBtn)mediaBtn.textContent=t('openLocalMedia','Open local media');renderAll();});if(!settings.ageGateAccepted){$('#ageGateOverlay').classList.remove('hidden');}else{$('#messageInput').focus();if(!state.setup?.completed)openSetup(false);}if(settings.updateChannelConfigured)checkUpdates(true);}catch(err){document.body.textContent=`Eidovara could not initialize: ${err?.message||err}`;} })();
