const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let state = null, settings = null, sending = false;
let mediaQueue = [], mediaIndex = -1;
const views = { chat: $('#chatView'), dashboard: $('#dashboardView'), apps: $('#appsView'), memory: $('#memoryView'), identity: $('#identityView'), settings: $('#settingsView') };

function activeConversation(){ return state?.conversations?.find(c=>c.id===state.activeConversationId) || state?.conversations?.[0]; }
function fmt(ts){ try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(ts));}catch{return '';} }
function setView(name){ Object.values(views).forEach(v=>v.classList.remove('active')); views[name].classList.add('active'); $('#viewTitle').textContent = name==='chat' ? (activeConversation()?.title || 'Conversation') : ({dashboard:'Dashboard',apps:'Apps & Gaming',memory:'Memory',identity:'Identity & continuity',settings:'Settings'}[name]); if(innerWidth<861) $('#sidebar').classList.remove('open'); }
function el(tag, cls, text){ const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; }
function setupCategories(){return $$('input[name="setupCategory"]:checked').map(x=>x.value);}
function toggleStreamSetup(){$('#setupStreamFields').classList.toggle('hidden',!setupCategories().includes('stream-helper'));}
function openSetup(reconfigure=false){const setup=state.setup||{};$$('input[name="setupCategory"]').forEach(x=>{x.checked=(setup.categories||[]).includes(x.value);});$('#setupCustomNeeds').value=setup.customNeeds||'';$('#setupObsUrl').value=setup.stream?.obsWebSocketUrl||'ws://127.0.0.1:4455';$('#setupStreamGoals').value=setup.stream?.goals||'';$('#cancelSetupBtn').classList.toggle('hidden',!reconfigure&&!setup.completed);$('#setupStatus').textContent='';toggleStreamSetup();$('#setupOverlay').classList.remove('hidden');}
async function openAdmin(){const status=await window.soul.adminStatus();$('#adminOverlay').classList.remove('hidden');$('#adminLoginStatus').textContent='';$('#adminPassword').value='';$('#adminLoginForm').classList.toggle('hidden',status.authorized);$('#adminPanelForm').classList.toggle('hidden',!status.authorized);if(status.authorized){$('#adminEdition').value=status.edition;$('#adminStoreUrl').value=status.storeUrl||'';$('#adminPanelStatus').textContent=`Unlocked until ${new Date(status.expiresAt).toLocaleTimeString()}.`;}else $('#adminPassword').focus();}

function renderConversations(){ const list=$('#conversationList'); list.textContent=''; for(const c of state.conversations){ const row=el('button','conversation'+(c.id===state.activeConversationId?' active':'')); row.type='button'; const label=el('span','label',c.title||'Conversation'); const del=el('button','delete','×'); del.type='button'; del.title='Delete conversation'; del.addEventListener('click',async e=>{e.stopPropagation(); if(state.conversations.length<=1)return; state=await window.soul.deleteConversation(c.id); renderAll();}); row.append(label,del); row.addEventListener('click',async()=>{state=await window.soul.selectConversation(c.id); renderAll();setView('chat');}); list.append(row); } }
function externalLink(url,label){const a=el('button','web-link',label);a.type='button';a.addEventListener('click',()=>window.soul.openExternal(url));return a;}
function currentPlayer(){return mediaQueue[mediaIndex]?.type==='video'?$('#videoPlayer'):$('#audioPlayer');}
function loadMedia(index,autoplay=true){if(!mediaQueue.length)return;mediaIndex=(index+mediaQueue.length)%mediaQueue.length;const item=mediaQueue[mediaIndex],audio=$('#audioPlayer'),video=$('#videoPlayer'),player=item.type==='video'?video:audio;audio.pause();video.pause();audio.classList.toggle('hidden',item.type==='video');video.classList.toggle('hidden',item.type!=='video');player.src=item.url;$('#mediaTitle').textContent=item.title||'Untitled media';$('#mediaKind').textContent=`${item.type} · ${mediaIndex+1} of ${mediaQueue.length}`;$('#mediaFavoriteBtn').textContent='♡';$('#mediaDock').classList.remove('hidden');if(autoplay)player.play().catch(()=>{});}
function playMedia(items,index){mediaQueue=items.filter(m=>m.type==='audio'||m.type==='video');const selected=items[index];loadMedia(Math.max(0,mediaQueue.indexOf(selected)));}
function renderResearch(target,research){if(!research)return;const panel=el('div','research-panel');panel.append(el('div','research-title',`Internet results · ${fmt(research.fetchedAt)}`));for(const s of research.sources||[]){const row=el('div','research-source');row.append(externalLink(s.url,s.title),el('small','',s.description||''));panel.append(row);}if(research.media?.length){const grid=el('div','media-grid');research.media.forEach((m,index)=>{const card=el('div','media-card');if(m.type==='image'){const img=document.createElement('img');img.src=m.url;img.alt=m.title;img.loading='lazy';card.append(img);}else{const play=el('button','media-launch',m.type==='audio'?'▶ Play audio':'▶ Play video');play.type='button';play.addEventListener('click',()=>playMedia(research.media,index));card.append(play);}card.append(externalLink(m.sourceUrl,m.title));grid.append(card);});panel.append(grid);}target.append(panel);}
function renderMessages(){ const box=$('#messages'); box.textContent=''; const c=activeConversation(); const messages=c?.messages||[]; $('#welcome').classList.toggle('hidden',messages.length>0); for(const m of messages){ const wrap=el('div',`message ${m.role==='assistant'?'assistant':'user'}`); if(m.role==='assistant'){ const av=el('div','soul-mark avatar'); av.append(el('span')); wrap.append(av); } const content=el('div'); const bubble=el('div','bubble',m.content); const meta=el('div','message-meta',fmt(m.at)); content.append(bubble);renderResearch(content,m.webResearch);content.append(meta);wrap.append(content); box.append(wrap); } requestAnimationFrame(()=>{$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight;}); }
function renderMemory(){ const box=$('#memoryCards'); box.textContent=''; const mem=[...(state.memories||[])].reverse(); if(!mem.length){box.append(el('div','empty','No durable memories yet.'));return;} for(const m of mem){ const card=el('div','card memory-card'); const body=el('div'); const p=el('div','',m.content); const sm=el('small','',`${m.active?'active':'inactive'} · ${m.kind} · confidence ${Math.round((m.confidence||0)*100)}%`); body.append(p,sm); const b=el('button','forget',m.active?'Forget':'Inactive'); b.type='button'; b.disabled=!m.active; b.addEventListener('click',async()=>{await window.soul.forget(m.id);state=await window.soul.snapshot();renderAll();}); card.append(body,b); box.append(card); } }
function renderIdentity(){ const sm=state.continuity.selfModel; const self=$('#selfModel'); self.textContent=''; for(const [k,v] of [['Name',sm.name],['Architecture',sm.architecture],['Protected identity',String(sm.protectedIdentity)],['Core values',sm.coreValues.join(', ')]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));self.append(r);} const traits=$('#traits');traits.textContent='';for(const [k,v] of Object.entries(state.personality).filter(([,v])=>typeof v==='number')){const r=el('div','trait');r.append(el('span','',k),(()=>{const b=el('div','bar');const f=el('div','fill');f.style.width=`${Math.round(v*100)}%`;b.append(f);return b;})(),el('span','',`${Math.round(v*100)}%`));traits.append(r);} const rel=$('#relationship');rel.textContent='';for(const [k,v] of [['Style',state.relationship.style],['Temporary initiative',String(state.relationship.temporaryInitiative)],['Trust',`${Math.round(state.relationship.trust*100)}%`],['Comfort',`${Math.round(state.relationship.comfort*100)}%`]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));rel.append(r);} const p=$('#policy');p.textContent='';for(const [k,v] of [['Mode',state.policy.mode],['Adult status confirmed',String(state.policy.adultStatusConfirmed)],['Adult Soul enabled',String(state.policy.adultSoulEnabled)],['Current consent',String(state.policy.currentConsent)],['Consent scope',state.policy.consentScope||'none'],['Active boundaries',String((state.policy.boundaries||[]).filter(b=>b.active).length)]]){const r=el('div','kv');r.append(el('span','',k),el('span','',v));p.append(r);} }
function renderStatus(){ const premium=settings?.edition==='premium'; $('#modePill').textContent=`${state.policy.mode==='adult'?'Adult Soul':'Standard Soul'} · ${premium?'Premium':'Free'}`; const labels={offline:'Soul Offline',local:'Local model',compatible:'Connected model'}; $('#providerLabel').textContent=labels[settings?.provider]||'Offline'; $('#editionTitle').textContent=premium?'Soul Premium':'Soul Free'; $('#editionDescription').textContent=premium?'Everything is enabled for this local installation.':'A complete core assistant with offline/local models, memory, media, backups, updates, and up to three linked apps.'; $('#upgradeBtn').classList.toggle('hidden',premium||!settings?.storeUrl); }
function applyTheme(){const t=settings?.theme||{};const root=document.documentElement;root.style.setProperty('--bg',t.background||'#080c16');root.style.setProperty('--panel',t.panel||'#101828');root.style.setProperty('--accent',t.accent||'#8f7cff');root.style.setProperty('--surface-opacity',`${Math.max(65,Math.min(100,Number(t.transparency)||96))}%`);document.body.classList.toggle('rgb-effects',Boolean(t.rgbEffects)&&!t.gamingMode);document.body.classList.toggle('gaming-mode',Boolean(t.gamingMode));}
function renderApps(){const grid=$('#appsGrid');grid.textContent='';const apps=settings?.apps||[];if(!apps.length){grid.append(el('div','empty','No applications added yet. Add a trusted .exe or Windows shortcut to build your workspace.'));return;}for(const app of apps){const card=el('div','app-card');const info=el('div','app-info');info.append(el('strong','',app.name),el('small','',app.path));const actions=el('div','app-actions');const launch=el('button','', 'Launch');launch.type='button';launch.addEventListener('click',async()=>{try{$('#appsStatus').textContent=`Launching ${app.name}…`;await window.soul.launchApplication(app.id);$('#appsStatus').textContent=`Launched ${app.name}.`;}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});const remove=el('button','secondary','Remove');remove.type='button';remove.addEventListener('click',async()=>{settings=await window.soul.removeApplication(app.id);applyTheme();renderApps();});actions.append(launch,remove);card.append(info,actions);grid.append(card);}}
async function refreshBackups(){const select=$('#backupSelect');select.textContent='';const backups=await window.soul.listBackups();for(const b of backups){const o=el('option','',`${new Date(b.createdAt).toLocaleString()} · ${Math.ceil(b.bytes/1024)} KB`);o.value=b.name;select.append(o);}if(!backups.length)select.append(el('option','','No backups yet'));$('#restoreBackupBtn').disabled=!backups.length;}
function renderDashboard(){const box=$('#dashboardGrid');box.textContent='';const items=[['Focus',state.assistant?.preferences?.focusMode||'general'],['Style',`${state.assistant?.preferences?.tone||'natural'} · ${state.assistant?.preferences?.responseLength||'balanced'}`],['Roles',(state.setup?.categories||[]).join(', ')||'not configured'],['Memory',`${(state.memories||[]).filter(x=>x.active).length} active`],['Apps',`${(settings?.apps||[]).length} connected`],['Privacy',settings?.provider==='offline'?'offline-first':'connected provider']];for(const [label,value] of items){const c=el('div','dashboard-card');c.append(el('small','',label),el('strong','',value));box.append(c);}}
function renderAll(){ renderConversations();renderMessages();renderDashboard();renderApps();renderMemory();renderIdentity();renderStatus();applyTheme();if($('#assistantAutonomy')){const p=state.assistant?.preferences||{},c=state.assistant?.capabilities||{};$('#assistantAutonomy').value=state.assistant?.autonomy||'balanced';$('#responseLength').value=p.responseLength||'balanced';$('#responseTone').value=p.tone||'natural';$('#focusMode').value=p.focusMode||'general';$('#assistantAccessibility').value=p.accessibility||'';$('#webResearchPolicy').value=c.webResearch||'ask';$('#mediaPlaybackPolicy').value=c.mediaPlayback||'confirm';$('#memoryLearning').checked=c.memoryLearning!=='disabled';$('#assistantInitiative').checked=state.assistant?.initiativeEnabled!==false;$('#assistantReflection').checked=state.assistant?.reflectionEnabled!==false;}$('#viewTitle').textContent=activeConversation()?.title||'Conversation'; }
function addTyping(){ const wrap=el('div','message assistant');const av=el('div','soul-mark avatar');av.append(el('span'));const b=el('div','bubble typing','Soul is thinking…');wrap.append(av,b);wrap.id='typing';$('#messages').append(wrap);$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight; }
function autoSize(){ const ta=$('#messageInput');ta.style.height='auto';ta.style.height=Math.min(180,ta.scrollHeight)+'px'; }
async function send(text){ text=String(text||'').trim();if(!text||sending)return;sending=true;$('#sendBtn').disabled=true;$('#messageInput').value='';autoSize(); if(!activeConversation()?.messages?.length) $('#welcome').classList.add('hidden'); const user=el('div','message user');const c=el('div');c.append(el('div','bubble',text));user.append(c);$('#messages').append(user);addTyping();try{const res=await window.soul.send(text);state=res.state;renderAll();if(res.providerError){const note=el('div','error-note',`Model connection issue: ${res.providerError}`);$('#messages').append(note);}if(res.internetError){const note=el('div','error-note',`Internet search issue: ${res.internetError}`);$('#messages').append(note);}}catch(err){$('#typing')?.remove();const note=el('div','error-note',String(err?.message||err));$('#messages').append(note);}finally{sending=false;$('#sendBtn').disabled=false;$('#messageInput').focus();} }

$('#chatForm').addEventListener('submit',e=>{e.preventDefault();send($('#messageInput').value);});
$('#messageInput').addEventListener('input',autoSize);$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.currentTarget.value);}});
$$('[data-starter]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.starter)));
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#newChatBtn').addEventListener('click',async()=>{state=await window.soul.newConversation();renderAll();setView('chat');$('#messageInput').focus();});
$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const v=$('#memoryInput').value.trim();if(!v)return;await window.soul.remember(v,{kind:'preference'});$('#memoryInput').value='';state=await window.soul.snapshot();renderAll();});
$$('[data-command]').forEach(b=>b.addEventListener('click',async()=>{setView('chat');await send(b.dataset.command);}));
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();$('#settingsStatus').textContent='Saving…';try{settings=await window.soul.saveSettings({provider:$('#providerSelect').value,endpoint:$('#endpointInput').value.trim(),model:$('#modelInput').value.trim(),apiKey:$('#apiKeyInput').value,clearApiKey:$('#clearKeyInput').checked,searchApiKey:$('#searchApiKeyInput').value,clearSearchApiKey:$('#clearSearchKeyInput').checked,theme:{background:$('#themeBackground').value,panel:$('#themePanel').value,accent:$('#themeAccent').value,transparency:Number($('#themeTransparency').value),rgbEffects:$('#themeRgb').checked,gamingMode:$('#gamingModeInput').checked}});$('#apiKeyInput').value='';$('#searchApiKeyInput').value='';$('#clearKeyInput').checked=false;$('#clearSearchKeyInput').checked=false;$('#settingsStatus').textContent='Settings saved.';applyTheme();renderStatus();}catch(err){$('#settingsStatus').textContent=String(err?.message||err);}});
$('#addAppBtn').addEventListener('click',async()=>{try{settings=await window.soul.addApplication();applyTheme();renderApps();$('#appsStatus').textContent='Application list updated.';}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});
$('#gamingModeInput').addEventListener('change',async()=>{try{settings=await window.soul.saveSettings({provider:settings.provider,endpoint:settings.endpoint,model:settings.model,theme:{...(settings.theme||{}),gamingMode:$('#gamingModeInput').checked}});applyTheme();$('#appsStatus').textContent=$('#gamingModeInput').checked?'Gaming mode enabled.':'Gaming mode disabled.';}catch(err){$('#appsStatus').textContent=String(err?.message||err);}});
$('#themeTransparency').addEventListener('input',()=>{$('#themeTransparencyValue').textContent=`${$('#themeTransparency').value}%`;});
$('#openDataBtn').addEventListener('click',()=>window.soul.openDataFolder());
$('#upgradeBtn').addEventListener('click',()=>{if(settings?.storeUrl)window.soul.openExternal(settings.storeUrl).catch(err=>{$('#settingsStatus').textContent=String(err?.message||err);});});
$('#assistantBehaviorForm').addEventListener('submit',async e=>{e.preventDefault();try{state=await window.soul.configureAssistant({autonomy:$('#assistantAutonomy').value,initiativeEnabled:$('#assistantInitiative').checked,reflectionEnabled:$('#assistantReflection').checked,responseLength:$('#responseLength').value,tone:$('#responseTone').value,focusMode:$('#focusMode').value,accessibility:$('#assistantAccessibility').value,webResearch:$('#webResearchPolicy').value,mediaPlayback:$('#mediaPlaybackPolicy').value,memoryLearning:$('#memoryLearning').checked?'enabled':'disabled'});$('#assistantBehaviorStatus').textContent='Behavior settings saved.';renderAll();}catch(err){$('#assistantBehaviorStatus').textContent=String(err?.message||err);}});
$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{setView('chat');send(b.dataset.quick);}));
$('#diagnosticsBtn').addEventListener('click',async()=>{const d=await window.soul.diagnostics();$('#diagnosticsText').textContent=JSON.stringify(d,null,2);$('#diagnosticsCard').classList.remove('hidden');});
async function checkUpdates(silent=false){try{const u=await window.soul.checkForUpdates();if(!u.configured){if(!silent)$('#updateStatus').textContent='This development build has no published release channel.';return;}if(u.available){$('#updateStatus').textContent=`Version ${u.version} is available.${u.notes?' '+u.notes:''}`;$('#installUpdateBtn').classList.remove('hidden');}else if(!silent){ $('#updateStatus').textContent=`Project Soul ${u.currentVersion} is current.`;}}catch(err){if(!silent)$('#updateStatus').textContent=String(err?.message||err);}}
$('#checkUpdateBtn').addEventListener('click',()=>checkUpdates(false));$('#installUpdateBtn').addEventListener('click',async()=>{try{$('#updateStatus').textContent='Downloading and verifying update…';const result=await window.soul.installUpdate();$('#updateStatus').textContent=result.cancelled?'Update cancelled.':'Verified installer launched.';}catch(err){$('#updateStatus').textContent=String(err?.message||err);}});
$$('input[name="setupCategory"]').forEach(x=>x.addEventListener('change',toggleStreamSetup));$('#openSetupBtn').addEventListener('click',()=>openSetup(true));$('#cancelSetupBtn').addEventListener('click',()=>$('#setupOverlay').classList.add('hidden'));$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();const categories=setupCategories();if(!categories.length&&!$('#setupCustomNeeds').value.trim()){$('#setupStatus').textContent='Choose at least one role or describe what you need.';return;}try{$('#setupStatus').textContent='Saving…';state=await window.soul.configureSetup({categories,customNeeds:$('#setupCustomNeeds').value,obsWebSocketUrl:$('#setupObsUrl').value,streamGoals:$('#setupStreamGoals').value});$('#setupOverlay').classList.add('hidden');renderAll();}catch(err){$('#setupStatus').textContent=String(err?.message||err);}});
$('#mediaPrevBtn').addEventListener('click',()=>loadMedia(mediaIndex-1));$('#mediaNextBtn').addEventListener('click',()=>loadMedia(mediaIndex+1));$('#mediaPlayBtn').addEventListener('click',()=>{const p=currentPlayer();if(!p)return;p.paused?p.play().catch(()=>{}):p.pause();});$('#mediaFavoriteBtn').addEventListener('click',async()=>{const item=mediaQueue[mediaIndex];if(!item)return;await window.soul.remember(`Favorite track: ${item.title}`);$('#mediaFavoriteBtn').textContent='♥';});$('#mediaSimilarBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)send(`Find music and audio similar to ${item.title}`);});$('#mediaSpotifyBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(`https://open.spotify.com/search/${encodeURIComponent(item.title)}`);});$('#mediaYouTubeBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(`https://www.youtube.com/results?search_query=${encodeURIComponent(item.title)}`);});$('#mediaSourceBtn').addEventListener('click',()=>{const item=mediaQueue[mediaIndex];if(item)window.soul.openExternal(item.sourceUrl);});$('#mediaCloseBtn').addEventListener('click',()=>{const p=currentPlayer();p?.pause();$('#mediaDock').classList.add('hidden');});$('#audioPlayer').addEventListener('ended',()=>loadMedia(mediaIndex+1));$('#videoPlayer').addEventListener('ended',()=>loadMedia(mediaIndex+1));
$('#backupBtn').addEventListener('click',async()=>{try{const b=await window.soul.createBackup();$('#backupStatus').textContent=`Created ${b.name}`;await refreshBackups();}catch(err){$('#backupStatus').textContent=String(err?.message||err);}});
$('#refreshBackupsBtn').addEventListener('click',()=>refreshBackups().catch(err=>{$('#backupStatus').textContent=String(err?.message||err);}));
$('#restoreBackupBtn').addEventListener('click',async()=>{const name=$('#backupSelect').value;if(!name||!confirm('Restore this backup and replace the current profile state?'))return;try{state=await window.soul.restoreBackup(name);renderAll();$('#backupStatus').textContent=`Restored ${name}`;}catch(err){$('#backupStatus').textContent=String(err?.message||err);}});
$('#resetBtn').addEventListener('click',async()=>{if(!confirm('Reset the current Soul profile and local conversation history?'))return;state=await window.soul.reset();renderAll();setView('chat');});
document.addEventListener('keydown',e=>{if(e.ctrlKey&&!e.shiftKey&&!e.altKey&&e.key.toLowerCase()==='a'){e.preventDefault();openAdmin().catch(err=>alert(String(err?.message||err)));}});
$('#adminCancelBtn').addEventListener('click',()=>$('#adminOverlay').classList.add('hidden'));
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();try{const status=await window.soul.adminLogin($('#adminPassword').value);$('#adminPassword').value='';$('#adminLoginForm').classList.add('hidden');$('#adminPanelForm').classList.remove('hidden');$('#adminEdition').value=status.edition;$('#adminStoreUrl').value=status.storeUrl||'';$('#adminPanelStatus').textContent=`Unlocked until ${new Date(status.expiresAt).toLocaleTimeString()}.`;}catch(err){$('#adminLoginStatus').textContent=String(err?.message||err);}});
$('#adminPanelForm').addEventListener('submit',async e=>{e.preventDefault();try{const status=await window.soul.adminSave({edition:$('#adminEdition').value,storeUrl:$('#adminStoreUrl').value.trim()});settings=await window.soul.getSettings();renderAll();$('#adminPanelStatus').textContent=`Saved ${status.edition} edition and store configuration.`;}catch(err){$('#adminPanelStatus').textContent=String(err?.message||err);}});
$('#adminLockBtn').addEventListener('click',async()=>{await window.soul.adminLogout();$('#adminOverlay').classList.add('hidden');});
$('#adminStoreBtn').addEventListener('click',()=>{const url=$('#adminStoreUrl').value.trim();if(!url){$('#adminPanelStatus').textContent='Configure an HTTPS store link first.';return;}window.soul.openExternal(url).catch(err=>{$('#adminPanelStatus').textContent=String(err?.message||err);});});

(async function init(){ try{[state,settings]=await Promise.all([window.soul.snapshot(),window.soul.getSettings()]);$('#providerSelect').value=settings.provider;$('#endpointInput').value=settings.endpoint||'';$('#modelInput').value=settings.model||'';$('#apiKeyInput').placeholder=settings.hasApiKey?'Stored securely — leave blank to keep':'API key';$('#searchApiKeyInput').placeholder=settings.hasSearchApiKey?'Stored securely — leave blank to keep':'Brave Search API key';const t=settings.theme||{};$('#themeBackground').value=t.background||'#080c16';$('#themePanel').value=t.panel||'#101828';$('#themeAccent').value=t.accent||'#8f7cff';$('#themeTransparency').value=t.transparency||96;$('#themeTransparencyValue').textContent=`${t.transparency||96}%`;$('#themeRgb').checked=Boolean(t.rgbEffects);$('#gamingModeInput').checked=Boolean(t.gamingMode);renderAll();setView('chat');$('#messageInput').focus();if(!state.setup?.completed)openSetup(false);if(settings.updateChannelConfigured)checkUpdates(true);}catch(err){document.body.textContent=`Project Soul could not initialize: ${err?.message||err}`;} })();
